<a href="https://colab.research.google.com/github/AnishShrestha09/numppy/blob/main/numpy12.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# A bank account has the following transactions:
import numpy as np

transactions = np.array([
5000, -2000, 15000, -4500, 7000,
-12000, 25000, -3000, 8000, -18000,
4500, 22008, -6008, 9000, -2500
])

# Extract deposits.
print(transactions[transactions > 0 ])


# Extract withdrawals.
print(transactions[transactions < 0 ])


# Calculate total deposits and withdrawals.
print(np.sum(transactions[transactions > 0 ]))
print(np.sum(transactions[transactions < 0 ]))
sum_pos = np.sum(transactions[transactions > 0 ])
sumneg = np.absolute(np.sum(transactions[transactions < 0 ]))


# Calculate absolute transaction values.
total_transaction = sum_pos + sumneg
print(total_transaction)


# Calculate net transaction amount.
a = np.sum(transactions[transactions > 0 ])-np.sum(transactions[transactions < 0 ])
print(a)


[ 5000 15000  7000 25000  8000  4500 22008  9000]
[ -2000  -4500 -12000  -3000 -18000  -6008  -2500]
95508
-48008
143516
143516


In [ ]:
# Find transactions whose absolute value is above the average absolute transaction.
mean = np.mean(np.absolute(transactions))
print(transactions[np.absolute(transactions) > mean])

# Find the largest deposit.
print(np.max(transactions))

# Find the largest withdrawal.
print(np.min(transactions))

# Create labels "Credit" and "Debit".
np.where(transactions > 0 ,"credit","debit")

# Find pergentage of transactions whose absolute value is greater than ₹10,000.
absolute_transaction = np.absolute(transactions)
a = len(transactions[transactions > 10000])
total = len(transactions)
percentage = a/total * 100
print(percentage)

# Reshape the data into 3 X 5.
b = transactions.reshape(3,5)
print(b)

# Calculate total transaction value for each row.
absolute_b = np.absolute(b)
print(np.sum(absolute_b, axis = 1))





[ 15000 -12000  25000 -18000  22008]
25000
-18000
20.0
[[  5000  -2000  15000  -4500   7000]
 [-12000  25000  -3000   8000 -18000]
 [  4500  22008  -6008   9000  -2500]]
[33500 66000 44016]


In [ ]:
# A factory has four machines operating for six days:
import numpy as np

production = np.array([
[120, 135, 128, 145, 150, 138],
[110, 125, 118, 130, 142, 135],
[160, 155, 170, 165, 180, 175],
[95, 105, 100, 115, 108, 120]
])


In [ ]:
# Calculate total production by machine.
print(np.sum(production ,axis = 1))

# Calculate total production by day.
print(np.sum(production, axis = 0))

# Calculate average production of each machine.
average = np.average(production, axis =1 )
print(average)

# Find the machine with the highest average production.
ind = np.argmax(average)
print(production[ind])


# Find the day with the lowest production.
abs = np.sum(production, axis = 0)
a = np.argmin(abs)
print(production[a])

[ 816  760 1005  643]
[485 520 516 555 580 568]
[136.         126.66666667 167.5        107.16666667]
[160 155 170 165 180 175]
[120 135 128 145 150 138]


In [ ]:
production = np.array([
[120, 135, 128, 145, 150, 138],
[110, 125, 118, 130, 142, 135],
[160, 155, 170, 165, 180, 175],
[95, 105, 100, 115, 108, 120]
])

# Find values above the overall average.
overall_avg = np.average(production)
production[production > overall_avg]


# Increase production values below 120 by 5%.
fivepercent = np.where(production < 120,production *1.05 ,production)
print(fivepercent)


# Extract alternate days.
print(production[: ,::2])

# Extract the last 3 days for machines 1 and 3.
production[[0,2],-3:]


# Create "High" and "Normal" labels based on the overall average.
np.where(production > overall_avg,"high","normal")


[[120.   135.   128.   145.   150.   138.  ]
 [115.5  125.   123.9  130.   142.   135.  ]
 [160.   155.   170.   165.   180.   175.  ]
 [ 99.75 110.25 105.   120.75 113.4  120.  ]]
[[120 128 150]
 [110 118 142]
 [160 170 180]
 [ 95 100 108]]


array([['normal', 'high', 'normal', 'high', 'high', 'high'],
       ['normal', 'normal', 'normal', 'normal', 'high', 'high'],
       ['high', 'high', 'high', 'high', 'high', 'high'],
       ['normal', 'normal', 'normal', 'normal', 'normal', 'normal']],
      dtype='<U6')

In [3]:
# Consider the following loan portfolio:

loan_amount = np.array([
100000, 250000, 500000, 750000,
120000, 350000, 900000, 450000
])

interest_rate = np.array([
8.5, 9.2, 8.8, 10.1,
7.9, 9.5, 10.5, 8.7
])


In [4]:
# Calculate annual interest for every loan.
annual_interest = (loan_amount * interest_rate)/100
print(annual_interest)

# Calculate total interest.
total_interest = np.sum(annual_interest)
print(total_interest)

# Calculate average interest.
print(np.mean(annual_interest))

# Find the loan generating the highest interest.
print(np.max(annual_interest))

# Find loans above ₹400,000 with interest rate above 9%.
interest_rate1 = (interest_rate> 9) & (loan_amount > 400000)
print(loan_amount[interest_rate1])

[ 8500. 23000. 44000. 75750.  9480. 33250. 94500. 39150.]
327630.0
40953.75
94500.0
[750000 900000]


In [9]:
# Categorize loans:
# Rate >= 10 - High
# Rate >= 9 - Medium
# Otherwise - Low
import numpy as np
loan_amount = np.array([
100000, 250000, 500000, 750000,
120000, 350000, 900000, 450000
])

interest_rate = np.array([
8.5, 9.2, 8.8, 10.1,
7.9, 9.5, 10.5, 8.7
])

mean = np.mean(loan_amount)

categories = np.where(interest_rate >= 10,"high",np.where(interest_rate >= 9,"medium","low"))
print(categories)

# Round interest to 2 decimal places.
print(annual_interest)

# Find median loan amount.
print(np.median(loan_amount))


# Find loans above median amount AND interest above average interest.
above = ((loan_amount > np.median(loan_amount)) & (loan_amount > mean))
print(loan_amount[above])



# Calculate standard deviation of interest rates.
np.std(interest_rate)




['low' 'medium' 'low' 'high' 'low' 'medium' 'high' 'low']
[ 8500. 23000. 44000. 75750.  9480. 33250. 94500. 39150.]
400000.0
[500000 750000 900000 450000]


np.float64(0.8031189202104504)