<a href="https://colab.research.google.com/github/AnishShrestha09/numppy/blob/main/numpy7.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# A simple grayscale image can be represented as a 2D NumPy array where each number represents pixel intensity.

# image = np.array([
# [10, 20, 30, 40, 50],
# [20, 30, 40, 50, 60],
# [30, 40, 50, 60, 70],
# [40, 50, 60, 70, 80],
# [50, 60, 70, 80, 90]
# ])
# Tasks
# Find the dimensions of the image.
# Find its shape.
# Find the total number of pixels.
# Display the center pixel.
# Extract the top-left 3 * 3 region
# Extract the bottom-right 2 x 2 region.
# Increase the intensity of the center 3 x 3 region by 20.
# Display the modified image.


In [2]:
import numpy as np

In [3]:
image = np.array([
[10, 20, 30, 40, 50],
[20, 30, 40, 50, 60],
[30, 40, 50, 60, 70],
[40, 50, 60, 70, 80],
[50, 60, 70, 80, 90]
])

In [4]:
# Find the dimensions of the image.
image.ndim

2

In [5]:
# Find its shape.
image.shape

(5, 5)

In [6]:
# Find the total number of pixels.
image.size

25

In [7]:
# Display the center pixel.
image[1:-1,1:-1]

array([[30, 40, 50],
       [40, 50, 60],
       [50, 60, 70]])

In [8]:
# Extract the top-left 3 * 3 region
image[:3,:3]


array([[10, 20, 30],
       [20, 30, 40],
       [30, 40, 50]])

In [9]:
# Extract the bottom-right 2 x 2 region.
image[-2:,-2:]


array([[70, 80],
       [80, 90]])

In [10]:
# Increase the intensity of the center 3 x 3 region by 20.
image[1:-1,1:-1] += 20


In [11]:
# Display the modified image.
image


array([[10, 20, 30, 40, 50],
       [20, 50, 60, 70, 60],
       [30, 60, 70, 80, 70],
       [40, 70, 80, 90, 80],
       [50, 60, 70, 80, 90]])

In [12]:
# A company stores quarterly revenue and expenses:

# financials = np.array([
# [120, 80],
# [150,90],
# [180, 110],
# [200, 130]
# ])
# Rows = Q1, 02, 03, 04
# Columns = Revenue, Expense

# Tasks
# Display Q2's complete financial data.
# Display all quarterly revenues.
# Display all quarterly expenses.
# Extract Q2 and Q3 data.
# Increase Q4 revenue by 15%.
# Reduce Q1 expense by 10%.
# Display the final financial matrix.

In [13]:
financials = np.array([
[120, 80],
[150,90],
[180, 110],
[200, 130]
])

In [14]:
# Display Q2's complete financial data.
financials[1]

array([150,  90])

In [15]:
# Display all quarterly revenues.
financials[:,0]

array([120, 150, 180, 200])

In [16]:
# Display all quarterly expenses.
financials[:,1]


array([ 80,  90, 110, 130])

In [17]:
# Extract Q2 and Q3 data.
financials[1:3]

array([[150,  90],
       [180, 110]])

In [20]:
# Increase Q4 revenue by 15%.
financials[-1, 0] = 1.15 * financials[-1, 0]

In [21]:
# Reduce Q1 expense by 10%.
financials[0,0] =0.9 * financials[0,0]

In [22]:
# Display the final financial matrix.
financials

array([[108,  80],
       [150,  90],
       [180, 110],
       [229, 130]])

In [23]:
# A classroom has 6 rows and 5 seats per row.

# Initially, all seats are empty.

# 0 = Empty
# 1 = Occupied
# Tasks
# Create a 6
# Mark the first seat of the first row as occupied.
# Mark all seats in the 3rd row as occupied.
# Mark the last two seats of the last row as occupied.
# Display the first 3 rows.
# Display the last 2 columns.
# Display the complete seating matrix.

# 5 array filled with zeros.

In [37]:
classroom = np.full((6,5),0)

In [38]:
# Mark the first seat of the first row as occupied.
classroom[0,0] = 1

In [39]:
classroom

array([[1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [40]:
# Mark all seats in the 3rd row as occupied.
classroom[2,:] = 1
classroom

array([[1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [41]:
# Mark the last two seats of the last row as occupied.
classroom[-1,-2:] = 1
print(classroom)

[[1 0 0 0 0]
 [0 0 0 0 0]
 [1 1 1 1 1]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 1 1]]


In [42]:
# Display the first 3 rows.
classroom[0:3]

array([[1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1]])

In [43]:
# Display the last 2 columns.
classroom[:,-2:]

array([[0, 0],
       [0, 0],
       [1, 1],
       [0, 0],
       [0, 0],
       [1, 1]])

In [44]:
# Display the complete seating matrix.

classroom

array([[1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 1, 1]])

In [48]:
# find the sum and avg
sales = np.array([100, 200, 300, 400, 500])

print(np.sum(sales))
print(np.average(sales))

1500
300.0


In [49]:
# find the minimum saleary
np.min(sales)

np.int64(100)

In [50]:
# find the maximum salary
np.max(sales)

np.int64(500)

In [51]:
sales = np.array([50, 30, 10, 190, 100 ])

np.median(sales)

np.float64(50.0)

In [55]:
a = len(sales)//2
print(sales[a])

10


In [56]:
# A teacher has recorded marks of 10 students:

# marks = np.array([72, 85, 91, 64, 78, 88, 95, 70, 82, 76])

# Find:

# Total marks
# Average marks
# Highest marks
# Lowest marks
# Difference between highest and lowest marks
# Index of the student with the highest marks

In [57]:
marks = np.array([72, 85, 91, 64, 78, 88, 95, 70, 82, 76])


np.sum(marks)

np.int64(801)

In [59]:
np.average(marks)


np.float64(80.1)

In [60]:
np.max(marks)

np.int64(95)

In [61]:
np.min(marks)

np.int64(64)

In [62]:
np.max(marks) - np.min(marks)

np.int64(31)

In [63]:
# Index of the student with the highest marks
np.argmax(marks)

np.int64(6)

In [64]:
# company's daily sales for 7 days are:

# sales = np.array([45000, 47000, 49000, 52000, 50000, 48000, 250000])

# Calculate the mean and median.

# Then determine which measure better represents a typical sales day when considering the unusually large sale.

# Also calculate the standard deviation.

# I

In [65]:

sales = np.array([45000, 47000, 49000, 52000, 50000, 48000, 250000])

In [66]:
np.mean(sales)

np.float64(77285.71428571429)

In [67]:
np.median(sales)

np.float64(49000.0)

In [68]:

# Then determine which measure better represents a typical sales day when considering the unusually large sale.
np.mean(sales)

np.float64(77285.71428571429)

In [69]:
# Also calculate the standard deviation.
np.std(sales)

np.float64(70540.18973143565)