<a href="https://colab.research.google.com/github/AnishShrestha09/pandas/blob/main/numpy5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
marks = np.array([70,80,65,90,75])

In [ ]:
marks[1:3] # last index is excluded

array([80, 65])

In [ ]:
marks[2:4]

array([65, 90])

In [ ]:
marks[0:4:2] #start,end,step

array([70, 65])

In [ ]:
marks[:3] # starting is zero

array([70, 80, 65])

In [ ]:
marks[3:] #end is last index

array([90, 75])

In [ ]:
marks[::] # start end step is default means 1

array([70, 80, 65, 90, 75])

In [ ]:
marks[::2] # print all the alternate elements

array([70, 65, 75])

In [ ]:
numbers = np.array([10, 20, 30, 40, 50, 60, 70])

print(numbers[1:4]) # 20 30 40
print(numbers[2:6]) # 30 40 50 60
print(numbers[0:3]) # 10 20 30

[20 30 40]
[30 40 50 60]
[10 20 30]


In [ ]:
numbers = np.array([10,20, 30, 40, 50])

print(numbers[2:]) # 30 40 50

[30 40 50]


In [ ]:
sales = np.array([100, 150, 200, 250, 300, 350])

print(sales[-3:]) # 250 300 350

[250 300 350]


In [ ]:
sales = np.array([100, 150, 200, 250, 300, 350])

print(sales[ :- 2]) # 100, 150, 200, 250

[100 150 200 250]


In [ ]:
numbers = np.array([10,20,30,40, 50, 60])

print(numbers [ :: 3]) #10 40

[10 40]


In [ ]:
# reverse the given array
numbers[::-1] # -1 is the step always come from backward

array([60, 50, 40, 30, 20, 10])

In [ ]:
marks = np.array([
[70,80,90,85],
[60,75,85,88],
[88, 92, 95,90],
[65,70,80,75]

])

In [ ]:
# get the marks of two rows
marks[:2]

array([[70, 80, 90, 85],
       [60, 75, 85, 88]])

In [ ]:
# second and third row
marks[1:3]

array([[60, 75, 85, 88],
       [88, 92, 95, 90]])

In [ ]:
# all rows and first 2 columns
marks[: ,:2] # first part is for row and other column

array([[70, 80],
       [60, 75],
       [88, 92],
       [65, 70]])

In [ ]:
# all row last and second last column
marks[:,-2:]

array([[90, 85],
       [85, 88],
       [95, 90],
       [80, 75]])

In [ ]:
marks[1:3,1:3]

array([[75, 85],
       [92, 95]])

In [ ]:
sales = np.array([
[100, 120, 150, 180],
[200, 220, 250, 270],
[150, 170, 190, 210]
])
print(sales[:, 1:3] * 1.10) # predict the output

[[132. 165.]
 [242. 275.]
 [187. 209.]]


In [ ]:
sales_ = sales[:,1:3]
withvat = sales_ * 1.1
print(withvat)

[[132. 165.]
 [242. 275.]
 [187. 209.]]


In [ ]:
prices = np. array([
1000, 1500, 2000, 2500, 3000, 3500
])
# product 3 - 5 receive 10 % discount
prices[2:5] * 0.9

array([1800., 2250., 2700.])

# DPP practice

In [ ]:
# A company has recorded its monthly revenue for the first 6 months:

# import numpy as np

# revenue = np.array([120000, 135000, 142000, 150000, 165000, 172000])

# Write a NumPy program to:

# Display the revenue of the third month.
# Display the revenue of the last month using negative indexing.
# Select the revenue from Month 2 to Month 5 using slicing.
# Increase the revenue of the last 3 months by 10%.
# Display the final revenue array.