<a href="https://colab.research.google.com/github/AnishShrestha09/numppy/blob/main/numpy4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# company has inventory information for 4 products across 3 warehouses.
# A

# Columns: Warehouse A, Warehouse B, Warehouse C

# import numpy as np

# inventory = np.array([
# [100,120,150],
# [80,90,110],
# [200,180,160],
# [50,70,90]

# I

# Perform the following:

# Display the inventory of Product 3 across all warehouses.
# Display the inventory of Warehouse B for all products.
# Warehouse A receives 20 additional units of every product. Update the array.
# The inventory of Product 4 in Warehouse C is incorrect. Change it to 100.
# Display the final inventory.

In [ ]:
import numpy as np

inventory = np.array([
[100,120,150],
[80,90,110],
[200,180,160],
[50,70,90]
])

In [ ]:
# Display the inventory of Product 3 across all warehouses.
product3 = inventory[2]
print(product3)

[200 180 160]


In [ ]:
# Display the inventory of Warehouse B for all products.
warehouse = inventory[:,1]
print(warehouse)


[120  90 180  70]


In [ ]:
# Warehouse A receives 20 additional units of every product. Update the array.
inventory[:,0] += 20
print(inventory)

[[120 120 150]
 [100  90 110]
 [220 180 160]
 [ 70  70  90]]


In [ ]:
# The inventory of Product 4 in Warehouse C is incorrect. Change it to 100.
inventory[3,2]= 100
print(inventory)

[[100 120 150]
 [ 80  90 110]
 [200 180 160]
 [ 50  70 100]]


In [ ]:
# Display the final inventory.
print(inventory)

[[120 120 150]
 [100  90 110]
 [220 180 160]
 [ 70  70 100]]


In [ ]:
# A weather application stores temperatures for 3 cities.

# Columns: Morning, Afternoon, Evening

# import numpy as np

# temperature = np. array([
# [24,35,28],
# [22, 32, 26],
# [27,38,30]

# Perform the following:

# Display the complete temperature data of the first city.
# Display all afternoon temperatures.
# Display the evening temperature of the last city using negative indexing.
# Increase all morning temperatures by 2C.
# The afternoon temperature of the second city was recorded incorrectly. Change it from 32 to
# Display the final temperature array.

In [ ]:
temperature = np. array([
[24,35,28],
[22, 32, 26],
[27,38,30]
])

In [ ]:
# Display the complete temperature data of the first city.
temperature[0]

array([24, 35, 28])

In [ ]:
# Display all afternoon temperatures.
temperature[:,1]


array([35, 32, 38])

In [ ]:
# Display the evening temperature of the last city using negative indexing.
temperature[-1 ,-1]


np.int64(30)

In [ ]:
# Increase all morning temperatures by 2C.
temperature[:,0] += 2
print(temperature)

[[26 35 28]
 [24 32 26]
 [29 38 30]]


In [ ]:
# The afternoon temperature of the second city was recorded incorrectly. Change it from 32 to 34
temperature[1,1]= 34
print(temperature)



[[26 35 28]
 [24 34 26]
 [29 38 30]]


In [ ]:
# Display the final temperature array.
print(temperature)

[[26 35 28]
 [24 34 26]
 [29 38 30]]
