<a href="https://colab.research.google.com/github/AnishShrestha09/numppy/blob/main/numpy15.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# A company records leads generated by four campaigns across five channels:
import numpy as np

leads = np.array([
[12000, 15000, 11000, 18000, 21000],
[14000, 13000, 17000, 19000, 22000],
[10000, 16000, 15000, 20000, 23000],
[18000, 17000, 19000, 21000, 25000]

])

# Find total leads generated by each campaign.
total_leads = np.sum(leads,axis=1)
print(total_leads)

# Find total leads generated by each channel.
total_leads1 = np.sum(leads,axis=0)
print(total_leads1)

# Find the campaign with maximum leads.
a= np.argmax(total_leads)
print(leads[a])


# Find the channel with maximum leads.
a= np.argmax(total_leads1)
print(a)




[ 77000  85000  84000 100000]
[54000 61000 62000 78000 91000]
[18000 17000 19000 21000 25000]
4


In [ ]:
# Find average leads per campaign.
average = np.average(leads,axis=1)
print(average)

# Find values above overall average.
overall_a = np.average(leads)
print(overall_a)
leads[leads>overall_a]

# Increase values below 15,000 by 10%.
increased_values = np.where(leads <15000,leads * 1.1,leads)
print(increased_values)

# Categorize values above median as "High" and others as "Low".
category = np.where(leads <np.median(leads),"high","low")
print(category)


# Extract every second channel.
leads[:,1::2]

[15400. 17000. 16800. 20000.]
17300.0
[[13200. 15000. 12100. 18000. 21000.]
 [15400. 14300. 17000. 19000. 22000.]
 [11000. 16000. 15000. 20000. 23000.]
 [18000. 17000. 19000. 21000. 25000.]]
[['high' 'high' 'high' 'low' 'low']
 ['high' 'high' 'high' 'low' 'low']
 ['high' 'high' 'high' 'low' 'low']
 ['low' 'high' 'low' 'low' 'low']]


array([[15000, 18000],
       [13000, 19000],
       [16000, 20000],
       [17000, 21000]])

In [ ]:
np.median(leads)

np.float64(17500.0)

## splitting arrays


In [ ]:
numbers = np.array([
10, 20, 30, 40,
50, 60, 70, 80
])

In [ ]:
a = numbers[:4]
b= numbers[4:]
print(a)
print(b)

[10 20 30 40]
[50 60 70 80]


In [ ]:
numbers_part = np.split(numbers,2)
print(numbers_part[0])
print(numbers_part[1])

[10 20 30 40]
[50 60 70 80]


In [ ]:
parts = np.split(numbers,4)

print(len(parts))
for i in range(len(parts)):
  if ((i==0) | (i==2)):
    print(parts[i])


4
[10 20]
[50 60]


In [ ]:
parts2 = np.split(numbers,[3,5])
print(parts2)


[array([10, 20, 30]), array([40, 50]), array([60, 70, 80])]


In [ ]:
data = np.array([
[1, 2, 3, 4],
[5,6,7,8],
[9, 10, 11, 12],
[13, 14, 15, 16]
])
parts = np.split(data, 2, axis=1)
parts

[array([[ 1,  2],
        [ 5,  6],
        [ 9, 10],
        [13, 14]]),
 array([[ 3,  4],
        [ 7,  8],
        [11, 12],
        [15, 16]])]

In [ ]:
data = np.arange(1,31).reshape(-1,2)
print(data)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]
 [13 14]
 [15 16]
 [17 18]
 [19 20]
 [21 22]
 [23 24]
 [25 26]
 [27 28]
 [29 30]]


In [ ]:
# first 8 rows training data
training_data =data[:-2]
print(training_data)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]
 [13 14]
 [15 16]
 [17 18]
 [19 20]
 [21 22]
 [23 24]
 [25 26]]


In [ ]:
sales = np.array([
120, 135, 128,
145, 150, 160,
155, 170, 165,
180, 190, 200

])

# etract 4 quarter sales from it

quarters = sales.reshape(4,3)
print(quarters)
np.sum(quarters,axis= 1)

[[120 135 128]
 [145 150 160]
 [155 170 165]
 [180 190 200]]


array([383, 455, 490, 570])

In [ ]:
quarter_sales = np.split(sales,4,axis=0)
print(np.sum(quarter_sales))

1898


In [ ]:
import numpy as np
orders = np.array([
[101, 3, 1200, 4.5],
[102, 5, 800, 3.8],
[103, 2, 2500, 4.8],
[104, 8, 450, 4.1],
[105, 4, 1800, 3.5],
[106, 6, 950, 4.7],
[107,3,2200, 4.9],
[108, 10, 600, 3.2],
[109, 7, 1500, 4.6],
[110, 2, 3000, 4.0],
[111, 5, 750, 3.9],
[112, 9, 1250, 4.8]
])
# Order_ID
# Quantity
# Price
# Rating



In [ ]:
# Inspect dimensions, shape and size.
print(orders.ndim)

# Extract the first 5 orders.
print(orders[:5])

# Extract the last 3 orders.
print(orders[-3:])

# Extract every second order.
print()
print(orders[1::2])

# Calculate revenue for every order.
revenue = orders[:,1] *orders[:,2]
print(revenue)

2
[[1.01e+02 3.00e+00 1.20e+03 4.50e+00]
 [1.02e+02 5.00e+00 8.00e+02 3.80e+00]
 [1.03e+02 2.00e+00 2.50e+03 4.80e+00]
 [1.04e+02 8.00e+00 4.50e+02 4.10e+00]
 [1.05e+02 4.00e+00 1.80e+03 3.50e+00]]
[[1.10e+02 2.00e+00 3.00e+03 4.00e+00]
 [1.11e+02 5.00e+00 7.50e+02 3.90e+00]
 [1.12e+02 9.00e+00 1.25e+03 4.80e+00]]

[[1.02e+02 5.00e+00 8.00e+02 3.80e+00]
 [1.04e+02 8.00e+00 4.50e+02 4.10e+00]
 [1.06e+02 6.00e+00 9.50e+02 4.70e+00]
 [1.08e+02 1.00e+01 6.00e+02 3.20e+00]
 [1.10e+02 2.00e+00 3.00e+03 4.00e+00]
 [1.12e+02 9.00e+00 1.25e+03 4.80e+00]]
[ 3600.  4000.  5000.  3600.  7200.  5700.  6600.  6000. 10500.  6000.
  3750. 11250.]


In [ ]:
# Calculate total and average revenue.
np.sum(revenue)

# Find the order with highest revenue.

orders[np.argmax(revenue)]

# Calculate median revenue.
print(np.median(revenue))

5850.0


In [ ]:
# Order_ID
# Quantity
# Price
# Rating

# Categorize orders:
# Revenue >= 15,000 High
# Revenue >= 7,500 + Medium
# Otherwise + Low

# Find orders where quantity >= 5 AND rating >= 4.5.
conditions= ( (orders[:,1]>=5) & (orders[:,-1]>=4.5))
print(orders[conditions])

# Find orders where price is above median OR rating is below 4.
condtion = ((orders[:,2] >np.mean(orders[:,2])) | ( orders[:,-1]<4))
orders[condtion]

# Give 10% discount to products whose price is above ₹1,000.

discountamount = np.where(orders[:,2]>=1000,0.1 *orders[:,2],0)
print(discountamount)

[[ 106.     6.   950.     4.7]
 [ 109.     7.  1500.     4.6]
 [ 112.     9.  1250.     4.8]]
[120.   0. 250.   0. 180.   0. 220.   0. 150. 300.   0. 125.]


In [ ]:
# Round discounted prices to 2 decimals.
np.round(discountamount,2)

# Calculate standard deviation of price.
print(np.std(orders[:,2]))

# Find 25th and 75th percentile of price.
print(np.percentile(orders[:,2],75))

# Find prices above the 75th percentile.
orders[orders[:,2]>np.percentile(orders[:,2],75)]

772.8015412913087
1900.0


array([[1.03e+02, 2.00e+00, 2.50e+03, 4.80e+00],
       [1.07e+02, 3.00e+00, 2.20e+03, 4.90e+00],
       [1.10e+02, 2.00e+00, 3.00e+03, 4.00e+00]])

In [ ]:
# percentage of orders with rating >= 3

total_orders = len(orders)
ratinggt3 = len(orders[:,-1]>=3)
print(ratinggt3)
percentage = ratinggt3/total_orders * 100
print(percentage)

12
100.0


In [ ]:
reshapedrev = revenue.reshape(3,4)
print(reshapedrev)

[[ 3600.  4000.  5000.  3600.]
 [ 7200.  5700.  6600.  6000.]
 [10500.  6000.  3750. 11250.]]


In [ ]:
# average revenue for each row

avgrev = np.mean(reshapedrev,1)
print(avgrev)

[4050. 6375. 7875.]


In [ ]:
revenue.flatten()

array([ 3600.,  4000.,  5000.,  3600.,  7200.,  5700.,  6600.,  6000.,
       10500.,  6000.,  3750., 11250.])

In [ ]:
import numpy as np

In [ ]:
marks = np.random.randint(0,101,10)

In [ ]:
marks

array([19, 43, 54, 30, 26, 16, 36, 62, 61, 16])

In [ ]:
print(np.random)

<module 'numpy.random' from '/usr/local/lib/python3.13/dist-packages/numpy/random/__init__.py'>


In [ ]:
np.random.random()

# genereates the value between 0 to 1

0.33230857633738453

In [ ]:
# generete 10 diff values
np.random.random(10)


array([0.04916248, 0.94924962, 0.02735778, 0.65501542, 0.92100396,
       0.23126645, 0.66564597, 0.03611323, 0.43288871, 0.09270628])

In [ ]:
np.random.random((3,4))

array([[0.60303385, 0.77995066, 0.61471488, 0.55645911],
       [0.78133653, 0.31610575, 0.36594309, 0.41409535],
       [0.81139199, 0.14916473, 0.07668325, 0.29233166]])

In [ ]:
# np.random.random(start,stop)

# start -> inclusive
# stop -> excluded

In [ ]:
np.random.randint(1,10)

7

In [ ]:
np.random.randint(1,10,6)

array([7, 8, 2, 1, 3, 7])

In [ ]:
# dice throwing 10 times
dice = np.random.randint(1,7,10)

# calc the prob of getting 5
print(dice)
len(dice[dice==5])/10 * 100

[5 5 2 1 5 6 2 2 2 2]


30.0

In [ ]:
# 5 * 4 matrix of random integers

np.random.randint(1,10,20).reshape(5,4)



array([[6, 2, 2, 4],
       [1, 8, 7, 4],
       [5, 8, 1, 6],
       [9, 3, 8, 8],
       [2, 5, 1, 2]])

In [ ]:
np.random.randint(1,10,(5,4))

array([[1, 1, 9, 9],
       [6, 1, 3, 4],
       [1, 5, 4, 1],
       [9, 4, 4, 7],
       [4, 4, 2, 9]])

In [ ]:
# we need floating values
np.random.uniform(20,30,10)

array([24.73359162, 29.48072071, 28.23860535, 22.83223806, 22.00589714,
       22.18627458, 26.21783962, 27.885709  , 28.57755761, 21.83514292])

In [ ]:
np.random.uniform(20,30,(3,4))

array([[20.66478578, 21.00546891, 23.73608313, 27.25240225],
       [27.12743208, 24.67154633, 20.76061999, 27.42811517],
       [27.12812149, 22.06555989, 27.35171093, 29.10598349]])

In [ ]:
np.random.seed(42)
n= np.random.randint(1,10,5)
print(n)

[7 4 8 5 7]


In [ ]:
np.random.seed(42)
n= np.random.randint(1,10,5)
print(n)

[7 4 8 5 7]


In [ ]:
#  random.choice

In [ ]:
colors = np.array(["orange","black","blue","white"])

In [ ]:
choice = np.random.choice(colors)
choice


np.str_('blue')

In [ ]:
np.random.choice(colors,3)

array(['white', 'orange', 'white'], dtype='<U6')

In [ ]:
# making no replacement
np.random.choice(colors,3,replace=False)

array(['white', 'blue', 'black'], dtype='<U6')