<a href="https://colab.research.google.com/github/AnishShrestha09/numppy/blob/main/numpy6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# A warehouse has 4 storage sections and 5 products.

# Initially, every product has a stock level of 100 units.

# Tasks
# Create a 4 x 5 array where every value is 100.
# Increase the stock of the first two sections by 20 units
# Reduce stock of the last two products by 10%.
# Display only the middle two sections.
# Display only the first three products.
# Display the bottom-right 2 x 2 portion of the matrix.

In [10]:
# Create a 4 x 5 array where every value is 100.
import numpy as np
product = np.full((4,5),100)
print(product)

# Increase the stock of the first two sections by 20 units
product[:2] += 20
print(product)


# Reduce stock of the last two products by 10%.
product[:,-2:] = 0.9 * product[:,-2:]


# Display only the middle two sections.
print(product[1:3])

# Display only the first three products.
print(product[:,:3])

# Display the bottom-right 2 x 2 portion of the matrix.
print(product[-2:, -2:])



[[100 100 100 100 100]
 [100 100 100 100 100]
 [100 100 100 100 100]
 [100 100 100 100 100]]
[[120 120 120 120 120]
 [120 120 120 120 120]
 [100 100 100 100 100]
 [100 100 100 100 100]]
[[120 120 120 108 108]
 [100 100 100  90  90]]
[[120 120 120]
 [120 120 120]
 [100 100 100]
 [100 100 100]]
[[90 90]
 [90 90]]


In [11]:
# A company has salary data for 4 employees:

# salary = np.array([
# [30000, 5000],
# [40000, 6000],
# [50000, 8000],
# [60000, 10000]

# })

# Column 1 = Basic Salary
# Column 2 = Allowance

# Tasks
# Display the complete information of the 2nd employee.
# Display all basic salaries.
# Display all allowances.
# Increase all allowances by ₹1,000.
# Increase the basic salary of the last two employees # by 10%.
# Display the final salary matrix.



In [12]:
salary = np.array([
[30000, 5000],
[40000, 6000],
[50000, 8000],
[60000, 10000]

])

In [15]:
# Tasks
# Display the complete information of the 2nd employee.
print(salary[1])

# Display all basic salaries.
print(salary[:,0])

# Display all allowances.
print(salary[:,1])

# Increase all allowances by ₹1,000.
salary[:,1] += 1000

# Increase the basic salary of the last two employees # by 10%.
salary[-2:,0] = 1.1 *salary[-2:,0]

# Display the final salary matrix.
print(salary)



[40000  7000]
[30000 40000 50000 60000]
[ 6000  7000  9900 12100]
[[30000  7000]
 [40000  8000]
 [55000 10900]
 [66000 13100]]


In [16]:
# A startup expects its monthly users to grow from 10,000 to 100,000 over 12 months.

# Tasks
# Generate monthly user targets using np. linspace()
# Create month numbers using np. arange().
# Display users expected in Month 1 and Month 12.
# Display users expected from Months 4 - 8.
# Increase all targets by another 15%.
# Display the updated targets for the last 4 months.

In [19]:
# Generate monthly user targets using np. linspace()
monthlyusers = np.linspace(10000, 100000,12)
print(monthlyusers)

# Create month numbers using np. arange().
months = np.arange(1,13)
print(months)

# Display users expected in Month 1 and Month 12.
print(monthlyusers[0])
print(monthlyusers[11])


# Display users expected from Months 4 - 8.
print(monthlyusers[3:8])


# Increase all targets by another 15%.
monthlyusers = monthlyusers * 1.15

# Display the updated targets for the last 4 months.
print(monthlyusers[-4:])

[ 10000.          18181.81818182  26363.63636364  34545.45454545
  42727.27272727  50909.09090909  59090.90909091  67272.72727273
  75454.54545455  83636.36363636  91818.18181818 100000.        ]
[ 1  2  3  4  5  6  7  8  9 10 11 12]
10000.0
100000.0
[34545.45454545 42727.27272727 50909.09090909 59090.90909091
 67272.72727273]
[ 86772.72727273  96181.81818182 105590.90909091 115000.        ]


In [20]:
# square root

In [21]:
numbers = np.array([4,9,16])

In [23]:
np.sqrt(numbers)
# answer always comes in float

array([2., 3., 4.])

In [24]:
np.sqrt(49)

np.float64(7.0)

In [28]:
x = np.array([3,5,8])
y = np.array([4,12,15])

# distance from origin
distance = np.sqrt(x**2 +y**2)
distance

array([ 5., 13., 17.])

In [35]:
# find the cube
x = np.array([1,2,3])
y = np.power(x,3)
y

array([ 1,  8, 27])

In [45]:
# find the cube
y**(1/3)

array([1., 2., 3.])

In [46]:
# find the absolute value
arr = np.array([-1,-2,1,2])
print(np.abs(arr))

[1 2 1 2]


In [48]:
# find the absolute value
absolute = np.sqrt(np.square(arr))
absolute

array([1., 2., 1., 2.])

In [53]:
values = np.array([10.2345, 20.6789, 30.4567])
print(np.around(values,2)) # rounds the value
print(np.around(values)) # prints ceiling value

[10.23 20.68 30.46]
[10. 21. 30.]


In [54]:
# round down
values = np.array([10.2345, 20.6789, 30.4567])
np.floor(values)

array([10., 20., 30.])

In [55]:
# round up
np.ceil(values)

array([11., 21., 31.])

In [64]:
#want the integer values only
values = np.array([1.1,7.9,8,-3.8])
np.trunc(values)

array([ 1.,  7.,  8., -3.])

In [ ]:
# An e-commerce company stores order information:

# orders = np.array([
# [1000, 2,500],
# [1001, 3, 750],
# [1002, 1,1200],
# [1003, 4,300],
# [1004, 2,900]
# ])
# Columns:

# Column 1 + Order ID
# Column 2 + Quantity
# Column 3 + Price per item

# Tasks
# Display the complete information of Order 1002.
# Display all quantities.
# Display all prices.
# Display the first 3 orders.
# Display the last 2 orders.
# Increase the price of the last 2 products by 10%.
# Increase the quantity of the first order by 1.
# Display the final dataset.
# Create a separate array containing only the quantity and price columns.
# Display the shape and size of the dataset.

In [79]:
# Column 1 + Order ID
# Column 2 + Quantity
# Column 3 + Price per item

orders = np.array([
      [1000, 2,500],
      [1001, 3, 750],
      [1002, 1,1200],
      [1003, 4,300],
      [1004, 2,900]
])
# Tasks
# Display the complete information of Order 1002.
orders[2]

# Display all quantities.
orders[:,1]

# Display all prices.
orders[:,2]

# Display the first 3 orders.
# orders[:3]

# Display the last 2 orders.
# orders[-2:]

# Increase the price of the last 2 products by 10%.
# orders[-2:,2] = orders[-2:,2] *1.1
# print(orders)

# Increase the quantity of the first order by 1.
# orders[0,1] += 1

# Display the final dataset.
# print(orders)

# Create a separate array containing only the quantity and price columns.
quantity_price = orders[:,-2:]
print(quantity_price)

# Display the shape and size of the dataset

print(quantity_price.size)
print(quantity_price.shape)



[[   2  500]
 [   3  750]
 [   1 1200]
 [   4  300]
 [   2  900]]
(5, 2)
