<a href="https://colab.research.google.com/github/AnishShrestha09/numppy/blob/main/numpy13.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# The coordinates of eight delivery locations are:
import numpy as np
points = np.array([
[3,4],
[5,12],
[8,15],
[7,24],
[9,40],
[12,35],
[15,20],
[6,8]
])
# Each row contains:

# [x, y]

# Calculate distance from the origin using:

# distance = V(x2 +y2)

# I

In [ ]:
# Extract x and y coordinates.
x = points[:,0] # x coordinate
y = points[:,1] # y coordinate

# Calculate distance for every location.
distance = np.sqrt(x**2 + y**2)
print(distance)

# Round distances to 2 decimals.
print(np.round(distance,2))

# Find nearest and farthest location.
print(np.max(distance))
print(np.min(distance))

# Find average distance.
print(np.mean(distance))

# Find locations above average distance.
criteria = distance > np.mean(distance)
print(points[criteria])

# Categorize:
# if >= 30 + Long
# elseif >= 15 - Medium
print(np.where(distance> 30,"long",np.where(distance > 15,"medium","short")))

[ 5. 13. 17. 25. 41. 37. 25. 10.]
[ 5. 13. 17. 25. 41. 37. 25. 10.]
41.0
5.0
21.625
[[ 7 24]
 [ 9 40]
 [12 35]
 [15 20]]
['short' 'short' 'medium' 'medium' 'long' 'long' 'medium' 'short']


In [ ]:
# Find percentage of Long-distance deliveries.

a = np.where(distance> 30,"long",np.where(distance > 15,"medium","short"))
b = len(a[a=="long"])
c = len(a)

d = b/c * 100
print(d)

# Flatten the coordinate array.
print(points.flatten())

# Find the size of the flattened array.
print(points.size)

25.0
[ 3  4  5 12  8 15  7 24  9 40 12 35 15 20  6  8]
16


In [ ]:
patients = np.array([
[101, 120, 85, 98],
[102, 135, 92, 96],
[103, 110, 78, 99],
[104, 150, 88, 94],
[105, 125, 95, 97],
[106, 160, 82, 93],
[107, 115, 90,98],
[108, 145, 87, 95],
[109, 130, 91, 96],
[110, 155, 80,92]
])
# Patient_ID, Heart_Rate, Oxygen_Level, Recovery_Score

# Calculate average heart rate.

print(np.mean(patients[:,1]))
# Calculate median oxygen level.
print(np.median(patients[:,2]))

# Find patients with heart rate above average AND oxygen below 90.
criteria = ((patients[:,1] >np.mean(patients[:,1])) & (patients[:,2]<90))
print(patients[criteria])


134.5
87.5
[[104 150  88  94]
 [106 160  82  93]
 [108 145  87  95]
 [110 155  80  92]]


In [ ]:
# Categorize recovery:
# >= 97 + Excellent
# >= 95 + Stable
# Otherwise + Monitor
a =patients[:,3]
b = np.where(a >= 97,"excellent",np.where(a>=95,"stable","monitor"))
print(b)
# Count each category.
excellent = len(b[b=="excellent"])
stable = len(b[b=="stable"])
monitor = len(b[b=="monitor"])
print(excellent,stable,monitor)


# Find patient with highest heart rate.
highest = np.argmax(patients[:,1])
patients[highest]

# Calculate standard deviation of oxygen levels.
print(np.std(patients[:,1]))

# Find oxygen levels more than 1 standard deviation below the mean.
avg_oxygenlevel = np.mean(patients[:,2])
std = np.std(patients[:,2])
sorted = np.sort(patients[:,2])
print(sorted[patients[:,2]<avg_oxygenlevel])

# Extract the last 3 patients.
patients[-3:]

# Flatten the measurement data and calculate its mean.



['excellent' 'stable' 'excellent' 'monitor' 'excellent' 'monitor'
 'excellent' 'stable' 'stable' 'monitor']
4 3 3
16.5
[78 82 88 95]


array([[108, 145,  87,  95],
       [109, 130,  91,  96],
       [110, 155,  80,  92]])

In [ ]:
# concatenate 2 strings
january = np.array([120, 150, 180])
february = np.array([140, 160, 200])
march = np.array([140, 160, 200])


months =np.concatenate((january,february,march))
months

array([120, 150, 180, 140, 160, 200, 140, 160, 200])

In [ ]:
a = np.array([
[1, 2],
[3,4]
])
b = np.array([
[5,6],
[7,8]
])

In [ ]:
np.concatenate((a,b), axis = 1)

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [ ]:
# Inventory across four stores and five products:

inventory = np.array([
[12, 45, 8, 32, 20],
[5, 60, 15, 25, 10],
[30,18, 6,40, 22],
[9, 55, 12, 28, 7]
])
# Calculate total inventory per store.
# Calculate total inventory per product.
# Find the store with highest inventory.
# Find the product with lowest total inventory.
# Extract inventory values below 10.
# Count items that require replenishment.
# Create "Reorder" / "OK" labels.
# Increase inventory below 10 by 20%.
# Round the resulting inventory.
# Find median inventory.
# Extract the last two products.
# Flatten the inventory and calculate standard deviation.

In [ ]:
# Consider the following daily prices:

prices = np.array([
820, 835, 810, 850, 875,
860, 890, 910, 895, 930,
945, 920, 960, 975, 990
])
# Calculate the change between consecutive days.
# Calculate absolute price movement.
# Find the largest movement.
# Find average movement.
# Find movements above average.
# Calculate percentage change between consecutive days.
# Round percentage changes to 2 decimals.
# Find days where price increased by more than 2%.
# Find maximum, minimum and range.
# Reshape prices into 3
# Find average price of each row.

# 5.

In [ ]:
leads = np.array([
        [12000, 15000, 11000, 18000, 21000],
        [14000, 13000, 17000, 19000, 22000],
        [10000, 16000, 15000, 20000, 23000],
        [18000, 17000, 19000, 21000, 25000]
      ])

# Find total leads generated by each campaign.
# Find total leads generated by each channel.
# Find the campaign with maximum leads.
# Find the channel with maximum leads.
# Find average leads per campaign.
# Find values above overall average.
# Increase values below 15,000 by 10%.
# Round the resulting values.
# Categorize values above median as "High" and others as "Low".
# Extract every second channel.

In [4]:
# Consider the following e-commerce dataset:
import numpy as np
orders = np.array([
[101, 3, 1200, 4.5],
[102, 5, 800, 3.8],
[103, 2, 2500,4.8],
[104, 8, 450, 4.1],
[105, 4, 1800, 3.5],
[106, 6, 950, 4.7],
[107, 3,2200, 4.9],
[108, 10, 600, 3.2],
[109, 7, 1500, 4.6],
[110, 2, 3000, 4.0],
[111, 5, 750, 3.9],
[112, 9, 1250, 4.8]
])
# Order ID # Quantity # Price # Rating

In [19]:
# Inspect dimensions, shape and size.
print(orders.ndim)
print(orders.shape)
print(orders.size)

# Extract the first 5 orders.
print(orders[:5])

# Extract the last 3 orders.
print(orders[-3:])

# Extract every second order.
print(orders[::2])

# Calculate revenue for every order.
quantity = orders[:,1]
price = orders[:,2]
revenue = price * quantity
print(revenue)

# Calculate total and average revenue.
print(np.sum(revenue))
print(np.average(revenue))

# Find the order with highest revenue.
print(orders[np.argmax(revenue)])

# Calculate median revenue.
print(np.median(revenue))

# Categorize orders:
# Revenue >= 15,000 + High
# Revenue >= 7,500 + Medium
# Otherwise + Low

categorize = np.where(revenue > 15000,"high",np.where(revenue > 7500,"medium","low"))
print(categorize)

# Find orders where quantity >= 5 AND rating >= 4.5.
cat = ((orders[:,1] >=5) &(orders[:,3] >=4.5) )
print(orders[cat])


# Find orders where price is above median OR rating is below 4.
median = np.median(orders[:,2])
cate = ((orders[:,2]> median) & (orders[:,3] <4.5))
orders[cate]


# Give 10% discount to products whose price is above ₹1,000.
discount_price = np.where(orders[:,2]>1000,0.1*orders[:,2],0)
print(discount_price)

# Round discounted prices to 2 decimals.
print(np.round(discount_price,2))

# Calculate standard deviation of price.
print(np.std(orders[:,2]))

print("Find 25th and 75th percentile of price.")
print(np.percentile(orders[:,2],25))
print(np.percentile(orders[:,2],75))


# Find prices above the 75th percentile.
print('# Find prices above the 75th percentile.')
print(orders[orders[:,2]>np.percentile(orders[:,2],75)])

# Find percentage of orders with rating > 4.5.
print("# Find percentage of orders with rating > 4.5.")
totalrating = len(orders[orders[:,-1]>4.5])
total = len(orders[:,-1])
percentage = totalrating /total * 100
print(percentage)


# Reshape revenue into 3 x 4.
reshaped = revenue.reshape(3,4)
print(reshaped)

# Calculate average revenue of each row.
print(np.average(reshaped, axis = 1))

# Flatten the revenue array.
print(reshaped.flatten())

# Calculate total revenue from orders having rating >= 4.5 AND revenue above average revenue.
categori = ((orders[:,-1]>4.5) & (revenue > np.average(revenue)))
print(np.sum(revenue[categori]))

2
(12, 4)
48
[[1.01e+02 3.00e+00 1.20e+03 4.50e+00]
 [1.02e+02 5.00e+00 8.00e+02 3.80e+00]
 [1.03e+02 2.00e+00 2.50e+03 4.80e+00]
 [1.04e+02 8.00e+00 4.50e+02 4.10e+00]
 [1.05e+02 4.00e+00 1.80e+03 3.50e+00]]
[[1.10e+02 2.00e+00 3.00e+03 4.00e+00]
 [1.11e+02 5.00e+00 7.50e+02 3.90e+00]
 [1.12e+02 9.00e+00 1.25e+03 4.80e+00]]
[[1.01e+02 3.00e+00 1.20e+03 4.50e+00]
 [1.03e+02 2.00e+00 2.50e+03 4.80e+00]
 [1.05e+02 4.00e+00 1.80e+03 3.50e+00]
 [1.07e+02 3.00e+00 2.20e+03 4.90e+00]
 [1.09e+02 7.00e+00 1.50e+03 4.60e+00]
 [1.11e+02 5.00e+00 7.50e+02 3.90e+00]]
[ 3600.  4000.  5000.  3600.  7200.  5700.  6600.  6000. 10500.  6000.
  3750. 11250.]
73200.0
6100.0
[ 112.     9.  1250.     4.8]
5850.0
['low' 'low' 'low' 'low' 'low' 'low' 'low' 'low' 'medium' 'low' 'low'
 'medium']
[[ 106.     6.   950.     4.7]
 [ 109.     7.  1500.     4.6]
 [ 112.     9.  1250.     4.8]]
[120.   0. 250.   0. 180.   0. 220.   0. 150. 300.   0. 125.]
[120.   0. 250.   0. 180.   0. 220.   0. 150. 300.   0. 125.]
