<a href="https://colab.research.google.com/github/AnishShrestha09/numppy/blob/main/numpy14.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
a = np.array([10, 20])
b = np.array([30,40])
c = np.array([50,60])

result = np.concatenate((a, b, c))

print(result)

[10 20 30 40 50 60]


In [ ]:
a = np.array([
[1,2],
[3,4]
])
b = np.array([
[5,6],
[7,8]
])

In [ ]:
np.concatenate((a,b))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [ ]:
week1 = np.array([1,2])
week2 = np.array([1,2])
week3= np.array([1,2])
np.hstack((week1,week2,week3))

array([1, 2, 1, 2, 1, 2])

In [ ]:
quantity_q1 = np.array([2,3,4,5,6]).reshape(-1,1)
quantity_q2 = np.array([2,3,4,5,6]).reshape(-1,1)
quantity_q3 = np.array([2,3,4,5,6]).reshape(-1,1)
quantity_q4 = np.array([2,3,4,5,6]).reshape(-1,1)

np.hstack((quantity_q1,quantity_q2,quantity_q3,quantity_q4))

array([[2, 2, 2, 2],
       [3, 3, 3, 3],
       [4, 4, 4, 4],
       [5, 5, 5, 5],
       [6, 6, 6, 6]])

In [ ]:
ids= np.array([101, 102, 103]).reshape(-1,1)
salary = np.array([50000, 65000, 72000]).reshape(-1,1)
experience = np.array([3,5,7]).reshape(-1,1)

In [ ]:
np.hstack((ids,salary,experience))

array([[  101, 50000,     3],
       [  102, 65000,     5],
       [  103, 72000,     7]])

In [ ]:
np.column_stack((ids,salary,experience))

array([[  101, 50000,     3],
       [  102, 65000,     5],
       [  103, 72000,     7]])

In [ ]:
quantity = np.array([2, 5,3,4])
price = np.array([100, 200, 150, 300])

revenue = quantity * price

np.column_stack((quantity,price,revenue))

array([[   2,  100,  200],
       [   5,  200, 1000],
       [   3,  150,  450],
       [   4,  300, 1200]])

In [13]:
# Consider the following daily prices:
import numpy as np
prices = np.array([
820, 835, 810, 850, 875,
860, 890, 910, 895, 930,
945, 920, 960, 975, 990

])



a= prices[:-1]
b= prices[1:]


pricesdiff = b-a
# Calculate percentage change between consecutive days.
percentchange = pricesdiff/b * 100
print(percentchange)

# Round percentage changes to 2 decimals.
print(np.round(percentchange,2))

# Find days where price increased by more than 2%.
print(percentchange > 2)

# Find maximum, minimum and range.
print(np.max(percentchange))
print(np.min(percentchange))
print(np.max(percentchange)-np.min(percentchange))

# Reshape prices into 3 X 5
reshaped = prices.reshape(3,5)

# Find average price of each row.
np.mean(reshaped,axis = 1)

# Calculate the change between consecutive days.


# Calculate absolute price movement.
# Find the largest movement.
# Find average movement.
# Find movements above average.



[ 1.79640719 -3.08641975  4.70588235  2.85714286 -1.74418605  3.37078652
  2.1978022  -1.67597765  3.76344086  1.58730159 -2.7173913   4.16666667
  1.53846154  1.51515152]
[ 1.8  -3.09  4.71  2.86 -1.74  3.37  2.2  -1.68  3.76  1.59 -2.72  4.17
  1.54  1.52]
[False False  True  True False  True  True False  True False False  True
 False False]
4.705882352941177
-3.0864197530864197
7.792302106027597


array([838., 897., 958.])

In [ ]:
a= prices[:-1]
b= prices[1:]

pricesdiff = b-a

In [ ]:
np.absolute(pricesdiff)

array([ 15,  25,  40,  25,  15,  30,  20,  15,  35,  15,  25,  40,  15,
       975])