<a href="https://colab.research.google.com/github/AnishShrestha09/numppy/blob/main/numpy16.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Installing Python Libraries
To install a library, use the `!pip install` command in a code cell. For example, to install the `gdown` library (or any other package):

In [ ]:
!pip install gdown

Once the installation completes, you can import and use the library as usual in subsequent cells.

In [ ]:
import numpy as np

In [ ]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [ ]:
np.zeros(4)

array([0., 0., 0., 0.])

In [ ]:
np.full((4,5),4)

array([[4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4]])

In [ ]:
np.full(5,10)

array([10, 10, 10, 10, 10])

In [ ]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
np.linspace(0,100,5)

array([  0.,  25.,  50.,  75., 100.])

In [ ]:
np.random.randint(1,100,10)

array([88, 51, 41, 97, 81, 96, 28, 81, 99, 19])

In [ ]:
np.random.randint(1,100)

99

In [ ]:
arr = np.array([10, 20, 30, 40, 50])


In [ ]:
arr.shape

(5,)

In [ ]:
arr.size

5

In [ ]:
arr.dtype

dtype('int64')

In [ ]:
data = np.array([
[10, 20, 30],
[40,50,60]
])
print(data.ndim)
print(data.shape)
print(data.size)
print(data.dtype)

2
(2, 3)
6
int64


In [ ]:
arr = np.array([10, 20, 30, 40, 50])

In [ ]:
arr[1:4] # 20 30 40
arr[:3] # 10 20 30
arr[2:] # 30 40 50
arr[::2] # 10 30 50
arr[::-1] # 50 40 30 20 10

array([50, 40, 30, 20, 10])

In [ ]:
data = np.array([
[10, 20, 30],
[40,50,60]
])
print(data[:2, :2])
# 10 20
# 40 50


print(data[:, :2])
# 10 20
# 40 50

print(data[1:, 1:])
# 40 50

[[10 20]
 [40 50]]
[[10 20]
 [40 50]]
[[50 60]]


In [ ]:
a = np.array([10,20,30])
b = np.array([1, 2, 3])

print(a + b)
print(a * b)

[11 22 33]
[10 40 90]


In [ ]:
np.sqrt(arr)
np.absolute(arr)
np.square(arr)
np.power(arr, 2)

array([ 100,  400,  900, 1600, 2500])

In [ ]:
np.exp(arr)

array([2.20264658e+04, 4.85165195e+08, 1.06864746e+13, 2.35385267e+17,
       5.18470553e+21])

In [ ]:
arr = np.arange(1,13)

In [ ]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [ ]:
arr.reshape(3,-1)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
a = np.array([1, 2, 3])
b = np.array([4, 5,6])

np.concatenate((a, b))

array([1, 2, 3, 4, 5, 6])

In [ ]:
np.split(arr,3)

[array([1, 2, 3, 4]), array([5, 6, 7, 8]), array([ 9, 10, 11, 12])]

In [ ]:
np.split(arr,[2,5,7])

[array([1, 2]), array([3, 4, 5]), array([6, 7]), array([ 8,  9, 10, 11, 12])]

In [ ]:
#Task: create a dataset having the following columns:

#  order_id,
#  quantity,
# unit_price,
# discount,
# rating

# with 20 rows



dataset = np.arange(1,101).reshape(-1,5)
dataset


array([[  1,   2,   3,   4,   5],
       [  6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15],
       [ 16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25],
       [ 26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35],
       [ 36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45],
       [ 46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55],
       [ 56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65],
       [ 66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75],
       [ 76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85],
       [ 86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95],
       [ 96,  97,  98,  99, 100]])

In [ ]:
order_id = np.arange(1,21)

In [ ]:
np.random.seed(42)
quantity = np.random.randint(1,10,20)
quantity

array([7, 4, 8, 5, 7, 3, 7, 8, 5, 4, 8, 8, 3, 6, 5, 2, 8, 6, 2, 5])

In [ ]:
np.random.seed(42)
unit_price = np.random.randint(2000,5000,20)
print(unit_price)

[2860 3294 3130 3095 3638 4169 2466 3238 2330 3482 4135 4919 2130 3685
 2769 4391 3515 4853 4433 3215]


In [ ]:
np.random.seed(42)
discount = np.random.randint(0,36,20)

In [ ]:
np.random.seed(42)
rating = np.random.randint(1,6,20)


In [ ]:
rating

array([4, 5, 3, 5, 5, 2, 3, 3, 3, 5, 4, 3, 5, 2, 4, 2, 4, 5, 1, 4])

In [ ]:
revenue = unit_price * quantity

In [ ]:
sales = np.column_stack((order_id,quantity,unit_price,discount,rating,revenue))

In [ ]:
sales

array([[    1,     7,  2860,    28,     4, 20020],
       [    2,     4,  3294,    14,     5, 13176],
       [    3,     8,  3130,     7,     3, 25040],
       [    4,     5,  3095,    20,     5, 15475],
       [    5,     7,  3638,    18,     5, 25466],
       [    6,     3,  4169,    22,     2, 12507],
       [    7,     7,  2466,    10,     3, 17262],
       [    8,     8,  3238,    10,     3, 25904],
       [    9,     5,  2330,    23,     3, 11650],
       [   10,     4,  3482,    35,     5, 13928],
       [   11,     8,  4135,    23,     4, 33080],
       [   12,     8,  4919,     2,     3, 39352],
       [   13,     3,  2130,    21,     5,  6390],
       [   14,     6,  3685,     1,     2, 22110],
       [   15,     5,  2769,    23,     4, 13845],
       [   16,     2,  4391,    29,     2,  8782],
       [   17,     8,  3515,     1,     4, 28120],
       [   18,     6,  4853,    20,     5, 29118],
       [   19,     2,  4433,    32,     1,  8866],
       [   20,     5,  3215,   

In [ ]:
campaigns = np.array([
[101, 10000, 800, 80, 5000, 7500],
[102, 15000, 1200, 150, 7000, 12000],
[103, 8000, 400, 30, 3000, 4200],
[104, 20000, 1800, 250, 9000, 18000],
[105, 12000, 600, 90, 6000, 8000],
[106, 18000, 1500, 220, 8000, 16000],
[107, 9000, 300, 20, 2500, 3000],
[108, 25000, 2200, 300, 11000, 24000]
])

In [ ]:
# Campaign_ID | Impressions | Clicks | Conversions | Cost | Revenue

# CTR = Clicks / Impressions * 100

# Conversion Rate = Conversions / Clicks * 100

# ROI = (Revenue - Cost) / Cost * 100

In [ ]:


print(" Find highest-revenue campaign.")
index = np.argmax(campaigns[:,-1])
print(campaigns[index])


print()


print("Find highest-ROI campaign.")
revenue = (campaigns[:,-1] - campaigns[:,-2]) / campaigns[:,-1] * 100
# print(revenue)
highest = np.argmax(revenue)
print(campaigns[highest])
print()
# Calculate average CTR.
print("Calculate average CTR.")
CTR = campaigns[:,2] / campaigns[:,1] * 100
print(np.average(CTR))
print()

# Calculate average ROI.
print(np.average(revenue))


# Find campaigns with above-average CTR and ROI.

 Find highest-revenue campaign.
[  108 25000  2200   300 11000 24000]

Find highest-ROI campaign.
[  108 25000  2200   300 11000 24000]

Calculate average CTR.
6.933333333333334

37.425595238095234
