<a href="https://colab.research.google.com/github/AnishShrestha09/numppy/blob/main/numpy2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
price = [100,200,300]

In [ ]:
import numpy as np


In [ ]:
np_price = np.array(price)
np_price2 = np_price + 0.2 * np_price
print(np_price2)

[120. 240. 360.]


In [ ]:
v = np.arange(1,10)

In [ ]:
v

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# lecture 2

In [ ]:
a= np.array([1,2,3,4,5.5])

In [ ]:
a

array([1. , 2. , 3. , 4. , 5.5])

In [ ]:
names = np.array(["pranharivansh","pyaroharivansh","shyamashyam"])

In [ ]:
names

array(['pranharivansh', 'pyaroharivansh', 'shyamashyam'], dtype='<U14')

In [ ]:
type(names)

numpy.ndarray

In [ ]:
a = np.array([True,False,False])


In [ ]:
a

array([ True, False, False])

In [ ]:
marks =np.array([[1,2,3],
                 [4,5,6]])

In [ ]:
marks

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
marks[0][1]

np.int64(2)

In [ ]:
marks[0,1]

np.int64(2)

In [ ]:
np.ones(5)*5 # always create the floating point

array([5., 5., 5., 5., 5.])

In [ ]:
np.full(6,2)

array([2, 2, 2, 2, 2, 2])

In [ ]:
np.full((2,3),3)

array([[3, 3, 3],
       [3, 3, 3]])

In [ ]:
# 0-10 all even numbers
# using linspace , arange

In [ ]:
a = np.arange(0,12,2)

In [ ]:
a

array([ 0,  2,  4,  6,  8, 10])

In [ ]:
b = np.linspace(0,10,6)

In [ ]:
b

array([ 0.,  2.,  4.,  6.,  8., 10.])

In [ ]:
a.dtype

dtype('int64')

In [ ]:
b.dtype

dtype('float64')

In [ ]:
a= np.array([10,20,20,30], dtype=float)

In [ ]:
a

array([10., 20., 20., 30.])

In [ ]:
a.dtype

dtype('float64')

In [ ]:
a = np.array([1.2,2.3] ,dtype=int)

In [ ]:
a

array([1, 2])

In [ ]:
a = np.array([1,2,3,-1,0,0], dtype=bool)

In [ ]:
a

array([ True,  True,  True,  True, False, False])

In [ ]:
# 0 means false
# none zero true

In [ ]:
import numpy as np
marks = np.array([1,2,3,4])
new_marks = marks +5
final_marks= new_marks * 1
print(marks)
print(new_marks)
print(final_marks)


[1 2 3 4]
[6 7 8 9]
[6 7 8 9]


In [ ]:
numbers = [1,2,3,4]
numbers2 = numbers*2
numbers3 = np.array(numbers)*2
print(numbers2)
print(numbers3)

[1, 2, 3, 4, 1, 2, 3, 4]
[2 4 6 8]


In [ ]:
prices = np.array([100,200,300])
discount = 0.2 * prices
new_discounted_price = prices - discount
print(new_discounted_price)

[ 80. 160. 240.]


In [ ]:
numbers = np.arange(2,21,3)


In [ ]:
numbers

array([ 2,  5,  8, 11, 14, 17, 20])

In [ ]:
numbers[0]
print(numbers[-1])
print(numbers[2:5])
print(numbers[:5])
print(numbers[5:])
len(numbers)
print(numbers*2)

20
[ 8 11 14]
[ 2  5  8 11 14]
[17 20]
[ 4 10 16 22 28 34 40]


In [ ]:
salary = np.full(20,20000)

In [ ]:
salary

array([20000, 20000, 20000, 20000, 20000, 20000, 20000, 20000, 20000,
       20000, 20000, 20000, 20000, 20000, 20000, 20000, 20000, 20000,
       20000, 20000])

In [ ]:
increament = salary *0.1
new_salary = salary + increament
print(new_salary)
print(new_salary*2)


[22000. 22000. 22000. 22000. 22000. 22000. 22000. 22000. 22000. 22000.
 22000. 22000. 22000. 22000. 22000. 22000. 22000. 22000. 22000. 22000.]
[44000. 44000. 44000. 44000. 44000. 44000. 44000. 44000. 44000. 44000.
 44000. 44000. 44000. 44000. 44000. 44000. 44000. 44000. 44000. 44000.]


In [ ]:
values = np.linspace(0,20,5)
doubled = values *2
print(values)
print(doubled)

[ 0.  5. 10. 15. 20.]
[ 0. 10. 20. 30. 40.]


In [ ]:
marks = np.array([
    [1,2,3,4],
    [5,6,7,8]
])
print(marks+ 5)
print(marks*2)
print(marks * marks)

[[ 6  7  8  9]
 [10 11 12 13]]
[[ 2  4  6  8]
 [10 12 14 16]]
[[ 1  4  9 16]
 [25 36 49 64]]


In [ ]:
# element wise subtraction, multiplication, add

In [ ]:
a= np.array([1,2,3,4])
b = np.array([4,5,6,7])
print(a+b)
print(b-a)
print(b*a)

[ 5  7  9 11]
[3 3 3 3]
[ 4 10 18 28]


In [ ]:
a= np.array([1,2,3,4])
b = np.array([4,5,6,7])
print(a+b)
print(b-a)
print(b*a)

[ 5  7  9 11]
[3 3 3 3]
[ 4 10 18 28]


In [ ]:
b = np.linspace(0,10,6)

In [ ]:
b

array([ 0.,  2.,  4.,  6.,  8., 10.])

In [ ]:
5/3

1.6666666666666667

In [ ]:
5/5

1.0

In [ ]:
arr = np.array([True,False,True])
array2 = arr *1

In [ ]:
array2

array([1, 0, 1])

In [ ]:
## error
arr = np.array(["shyamashyam", dtype=int])

SyntaxError: invalid syntax. Maybe you meant '==' or ':=' instead of '='? (1570987714.py, line 2)

# challenge question - DPP


In [ ]:
import numpy as np


In [ ]:
arra = np.array([65,72,80,88,91])

In [ ]:
arra

In [ ]:
arra1 = arra + 5

In [ ]:
arra1

In [ ]:
arra = np.array([100, 250, 400, 550, 800])
discount = 0.1 * arra
new_marks = arra - discount
print(new_marks)


In [ ]:
arra = np.array([30000, 35000, 40000, 45000, 50000])
arra1 = arra * 1.1
print(arra1)


### A student's marks are stored in a tuple:

(78, 85, 92, 67, 88)

Convert the tuple into a NumPy array and add 3 marks to every value.

M


In [ ]:
arra1 = (78, 85, 92, 67, 88)
arra2 = np.array(arra1)
print(type(arra2))
arra3 = arra2 + 3
print(arra3)

# A company records sales for four .quarters :

# Q1 = 125000
#-Q2= 148000
# Q3= 135000
# 04=172000

# Create a .NumPy .array.

# The company expects .next year's .sales .to. be . 15% higher than this year's.sales. Calculate the expected sales for .each

# Then .calculate the additional sales .expected in each quarter.

In [ ]:
arra2 = np.array([125000, 148000, 135000, 172000])
arra3 = arra2 * 1.15
print(arra3)
arra4 = arra3 - arra2
print(arra4)


Two branches of a company have inventory for five products.

Branch A = [120, 150, 180, 100, 200]
Branch B = [80, 130, 170, 120, 150]

Create two NumPy arrays.

Calculate:

Total inventory for each product.
Difference between Branch A and Branch B.
Combined inventory after receiving an additional 20 units of every product.
M W

In [ ]:
a = np.array([120, 150, 180, 100, 200])
b = np.array([80, 130, 170, 120, 150])
asum = a.sum()
bsum = b.sum()
diff = bsum- asum
print(diff)
c = a + b + 20



print(c)


A store sells four products.

Prices:

[250, 400, 750, 1200]

Units sold:

[12, 8,5,10]

Calculate the revenue generated by each product.

The store then wants to increase the revenue figures by 5% for forecasting purposes.


In [ ]:
prices= np.array([250, 400, 750, 1200])
units_sold = np.array([12, 8,5,10])
revenue = prices * units_sold
print(revenue)
new_revenue = revenue * 1.05
print(new_revenue)

In [ ]:
arr2.ndim

In [ ]:
#shape

In [ ]:
marks = np.array([1,2,3,4,5])

In [ ]:
marks.shape

In [ ]:
arr2 = np.array([
    [1,2,3],
    [4,5,6]
    ])

In [ ]:
arr2.shape

In [ ]:
arr2.size

In [ ]:
len(arr2)

In [ ]:
arr = np.array([1.5,2.5,3.5])
int_arr = arr.astype(int)
print(int_arr)

[1 2 3]


In [ ]:
arr

array([1.5, 2.5, 3.5])

In [ ]:
student_marks = np.array([
[78,85,90,88,76],
[92, 81, 85,89,95],
[67,72,70,75,68],
[88, 91, 94, 90, 87],
[76,80,79,82,85]
])

In [ ]:
print(student_marks.ndim)
print(student_marks.shape)
print(student_marks.size)
print(student_marks.dtype)
a = student_marks[0]
print(student_marks.shape[0])


2
(5, 5)
25
int64
417
5


In [ ]:
# A college wants to initialize a marks table for 5 students and 4 subjects.

# Initially, every student's marks are set to zero.

# Create this using NumPy.

# Then create another 5 * 4 array containing a default value of 50.

In [ ]:
a = np.zeros((5,4))
a.shape

(5, 4)

In [ ]:
a = np.full((5,4),50)
print(a)

[[50 50 50 50]
 [50 50 50 50]
 [50 50 50 50]
 [50 50 50 50]
 [50 50 50 50]]


In [ ]:
# Five students have scores:

# [45, 56, 67, 78,89]

# The teacher gives everyone 3 grace marks.

# After that, the college applies a 10% scaling factor to the adjusted scores.

# Calculate the final scores.

In [ ]:
marks = np.array([45, 56, 67, 78,89])
withgracemarks = marks + 3
print(withgracemarks)
adjustedscore = withgracemarks * 1.1
print(adjustedscore)


[48 59 70 81 92]
[ 52.8  64.9  77.   89.1 101.2]


In [ ]:
# A company wants to set targets from ₹20,000 to ₹1,00,000.

# Generate exactly 9 target values, equally spaced.

# Then create actual sales:

# [18000, 28000, 39000, 47000, 57000, 66000, 76000, 90000, 105000]

# Calculate the difference between actual and target.

In [ ]:
sales = np.array([18000, 28000, 39000, 47000, 57000, 66000, 76000, 90000, 105000])
target = np.linspace(20000,100000,9)
a = sales -  target
print(a)

[-2000. -2000. -1000. -3000. -3000. -4000. -4000.     0.  5000.]


In [ ]:
# A dataset contains:

# [10, 20, 30.5, 40, 50.75]

# Create a NumPy array and display its data type.

# Then create an integer version of the array.
# a
# Finally, multiply the integer array by 3.

In [ ]:
data = np.array([10, 20, 30.5, 40, 50.75])
print(data.dtype)
int_data = data.astype(int)
print(int_data)
print(int_data*3)

float64
[10 20 30 40 50]
[ 30  60  90 120 150]


In [ ]:
# A company has product prices:

# [499, 799, 1299, 1999, 2499]

# The company wants to:

# Increase all prices by 12%.
# Add ₹50 packaging charges.
# Calculate the final customer price.

In [ ]:
prices = np.array([499, 799, 1299, 1999, 2499])
increaseby12 = prices * 1.12
packingalso = increaseby12 + 50
print(packingalso)

[ 608.88  944.88 1504.88 2288.88 2848.88]


In [ ]:
# A website offers:

# First discount: 10%
# Second discount: 5% on the already discounted price

# Prices:

# [1000, 2000, 3000, 4000]

# Calculate the final prices.

In [ ]:
prices = np.array([1000, 2000, 3000, 4000])
discountedprice = 0.9 * prices
seconddiscount = 0.95 * discountedprice
print(seconddiscount)

[ 855. 1710. 2565. 3420.]


In [ ]:
# A business has monthly revenue:

# [80000, 95000, 110000, 125000, 140000, 155000]

# The expected growth rate is 12%.

# Calculate:

# Expected increase.
# Forecast revenue.
# Create a target revenue array using linspace() from ₹80,000 to ₹1,60,000 with exactly 6 values.
# MA

# Compare forecast revenue with the target.

In [ ]:
revenue = np.array([80000, 95000, 110000, 125000, 140000, 155000])
expected = revenue * 1.12
print(expected)
targetrevenue = np.linspace(80000,160000,6)
print(targetrevenue)
compare = expected - targetrevenue
print(compare)

[ 89600. 106400. 123200. 140000. 156800. 173600.]
[ 80000.  96000. 112000. 128000. 144000. 160000.]
[ 9600. 10400. 11200. 12000. 12800. 13600.]


In [ ]:
revenue = np.array([[80000, 95000],[ 110000, 125000]])

In [ ]:
revenue

array([[ 80000,  95000],
       [110000, 125000]])

In [ ]:
revenue[0,0]

np.int64(80000)

In [ ]:
# print all diagonal elements of array

In [ ]:
for i in range(len(revenue)):
  print(revenue[i,i])

80000
125000


In [ ]:
# A college stores marks of 4 students in 3 subjects: Maths, Science, and English.

# import numpy as np

# marks = np.array([
# [72,85,90],
# [65,78,82],
# [88,91,84],
# [70,76,80]
# ])
# Perform the following:

# Display the marks of the third student.
# Display the Science marks of the second student.
# Add 5 bonus marks to every student's English marks.
# Change the Maths marks of the fourth student to 75.
# Display the final marks array.

In [ ]:
marks = np.array([
[72,85,90],
[65,78,82],
[88,91,84],
[70,76,80]
])

In [ ]:
print(marks[2])
print(marks[0,2]+5)

[88 91 84]
95


In [ ]:
#  add bonus to all english marks
marks[:,2]+=5
marks

array([[72, 85, 95],
       [65, 78, 87],
       [88, 91, 89],
       [70, 76, 85]])

In [ ]:
# company records monthly sales for 3 branches. The columns represent January, February, and March.
# ARAAAN

# import numpy as np

# sales = np.array([
# [120, 150, 180],
# [100, 130,160],
# [200, 220, 250]

# Perform the following:

# Display the complete sales data of Branch 2.
# Display the sales of all branches in February.
# Increase the March sales of every branch by 10%.
# The January sales of Branch 1 were entered incorrectly. Change them from 120 to 135.
# Display the updated sales array.

In [ ]:
sales = np.array([
[120, 150, 180],
[100, 130,160],
[200, 220, 250]
])

In [ ]:
# complete sales of branch 2
print(sales[1])

# Display the sales of all branches in February.
print(sales[:,1])

# Increase the March sales of every branch by 10%.
sales[:,2] = 1.1*sales[:,2]
print(sales)
# The January sales of Branch 1 were entered incorrectly. Change them from 120 to 135.
sales[0,0] = 135

# Display the updated sales array.
print(sales)



[100 130 160]
[150 130 220]
[[120 150 198]
 [100 130 176]
 [200 220 275]]
[[135 150 198]
 [100 130 176]
 [200 220 275]]


In [ ]:
# An organization stores employee information as:

# Salary |

# import numpy as np

# employees = np. array([
# [30000, 2],
# [40000, 4],
# [50000, 6],
# [60000, 8]
# ])
# Experience

# Perform the following:

# Display the information of the last employee using negative indexing.
# Display the salary of the second employee.
# Increase the salary of the third employee by 15%.
# Add 1 year of experience to the first employee.

In [ ]:
employees = np. array([
[30000, 2],
[40000, 4],
[50000, 6],
[60000, 8]
])

In [ ]:
# Display the information of the last employee using negative indexing.
employees[-1]
print(employees[-1])


# Display the salary of the second employee.
employees[1]
print(employees[1,0])


# Increase the salary of the third employee by 15%.
employees[2,0]*= 1.15
print(employees[2,0])


# Add 1 year of experience to the first employee.
employees[0,1] +=1
print(employees[0,1])


[60000     8]
40000
87447
5


In [ ]:
# A company has inventory information for 4 products across 3 warehouses.

# Columns: Warehouse A, Warehouse B, Warehouse C

# import numpy as np

# inventory = np.array([
# [100, 120, 150],
# [80,90,110],
# [200, 180,160],
# [50,70,90]
# )]
# Perform the following:

# Display the inventory of Product 3 across all warehouses.
# M

# Display the inventory of Warehouse B for all products.
# Warehouse A receives 20 additional units of every product. Update the arr
# The inventory of Product 4 in Warehouse C is incorrect. Change it to 100.
# Display the final inventory.