<a href="https://colab.research.google.com/github/AnishShrestha09/numppy/blob/main/numpy10.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
# Give students this towards the end.

# employees = np. array([
# [101, 45000, 120000],
# [102, 60000, 180000],
# [103, 35000, 90000],
# [104, 75000, 250000],
# [105, 50000, 160000]
# ])
# I

# Columns:

# Employee_ID | Salary | Sales

# Employees with sales >= ₹150,000 receive 5% commission.

In [ ]:
employees = np. array([
[101, 45000, 120000],
[102, 60000, 180000],
[103, 35000, 90000],
[104, 75000, 250000],
[105, 50000, 160000]
])

In [ ]:
np.mean(employees, axis = 1)

array([ 55033.66666667,  80034.        ,  41701.        , 108368.        ,
        70035.        ])

In [ ]:
# Employees with sales >= ₹150,000 receive 5% commission else 2% commmision

employees[:,2] > 150000

bonus = np.where(employees[:,2] > 150000 , 0.05* employees[:,2], 0.02 * employees[:,2])
print(bonus)


[ 2400.  9000.  1800. 12500.  8000.]


In [ ]:
reaction = np.where(employees[:,2] > 200000 , "excellent",np.where(employees[:,2] > 150000,"good","improvement") )

In [ ]:
reaction

array(['improvement', 'good', 'improvement', 'excellent', 'good'],
      dtype='<U11')

In [ ]:
import numpy as np

sales = np.array([
120, 150, 180, 200,
220, 250, 270, 300,
320, 350, 380, 400
])

In [ ]:
sales.shape

(12,)

In [ ]:
qtr_sales = sales.reshape(4,3)
print(qtr_sales)
print(qtr_sales.shape)

[[120 150 180]
 [200 220 250]
 [270 300 320]
 [350 380 400]]
(4, 3)


In [ ]:
numbers = np.array([1, 2, 3, 4, 5, 6])
two_rows = numbers.reshape(2,3)

In [ ]:
two_rows

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
marks = np.array([
72, 81, 65, 90, 77,
88, 69, 91, 73, 84,
60, 75, 82, 79, 95,
68, 71, 86, 89, 93
])

In [ ]:
# 4*5
# sum of each row

In [ ]:
marks2 = marks.reshape(4,5)
print(np.sum(marks2, axis = 1))

[385 405 391 407]


In [ ]:
marks.reshape(2,-1)

array([[72, 81, 65, 90, 77, 88, 69, 91, 73, 84],
       [60, 75, 82, 79, 95, 68, 71, 86, 89, 93]])

In [ ]:
#  if i want 2 columns
marks.reshape(-1,2)

array([[72, 81],
       [65, 90],
       [77, 88],
       [69, 91],
       [73, 84],
       [60, 75],
       [82, 79],
       [95, 68],
       [71, 86],
       [89, 93]])

In [ ]:
matrix = np.array([
[10,20,30],
[40,50,60],
[70,80,90]
])

In [ ]:
matrix.flatten()

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
sales = np.array(
    [[
[100, 120, 150],
[90,110, 130],
[200, 220, 250]
],
                  [
[100, 120, 150],
[90,110, 130],
[200, 220, 250]
]
     ])

# want the average sales for all 9 months
a = sales.flatten()
print(np.mean(a))


152.22222222222223


In [ ]:
a  = np.arange(30)
print(a)

b = a.reshape(2,3,-1)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]


In [ ]:
b[0]

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [ ]:
b[0,:]

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [ ]:
# An e-commerce company records the quantity sold and selling price of 12 products.

quantity = np.array([2, 5, 8, 8, 4, 6, 10, 1, 7, 5, 9, 3])

price = np.array([
1200, 800, 1500, 4500, 2200, 900,
700, 1800, 650, 1300, 500, 2500
])

In [ ]:
# Calculate revenue for every product.
revenue = quantity * price
print(revenue)

# Calculate the total revenue.
total = np.sum(revenue)
print(total)

# Find the product index generating the highest revenue.
print(np.argmax(revenue))

# Extract the revenue of the last five products.
print(revenue[-5:])


[ 2400  4000 12000 36000  8800  5400  7000  1800  4550  6500  4500  7500]
100450
3
[1800 4550 6500 4500 7500]


In [ ]:
# Find products whose revenue is above the average revenue.
revenue[revenue > np.mean(revenue)]

# Apply a 10% discount only to products whose price is greater than ₹1,000.
discount = np.where(price > 1000,0.01 *price,0)
print(discount)

# Round the discounted prices to two decimal places.
print(np.round(discount,2))


# Calculate the total quantity sold.
print(np.sum(quantity))

# Find the median product price.
print(np.median(price))

# Identify products whose price is above the median and whose quantity is at least 5.
a = price[ (price > np.median(price)) & (quantity >= 5)]

print(a)


[12.  0. 15. 45. 22.  0.  0. 18.  0. 13.  0. 25.]
[12.  0. 15. 45. 22.  0.  0. 18.  0. 13.  0. 25.]
68
1250.0
[1500 4500 1300]


In [ ]:
# A college has performance scores for 24 assessments:

# scores = np. array ([
# 72, 81, 65, 90,
# 77, 88, 69, 91,
# 73, 84, 60, 75,
# 82, 79, 95, 68,
# 71, 86, 89, 93,
# 66, 74, 80, 87
# ])
# Assume there are 6 students and 4 assessments per student.

In [ ]:
scores = np. array ([
72, 81, 65, 90,
77, 88, 69, 91,
73, 84, 60, 75,
82, 79, 95, 68,
71, 86, 89, 93,
66, 74, 80, 87
])

(24,)

In [ ]:
# Verify the number of elements.
print(scores.shape)

# Reshape the array into a 6
a= scores.reshape(6,4)
print(a)

# Calculate the average score for each student.
print(np.mean(a, axis = 1))

# Find the highest score achieved by each student.
print(np.max(a,axis = 1))


(24,)
[[72 81 65 90]
 [77 88 69 91]
 [73 84 60 75]
 [82 79 95 68]
 [71 86 89 93]
 [66 74 80 87]]
[77.   81.25 73.   81.   84.75 76.75]
[90 91 84 95 93 87]


In [ ]:
# Find the student index having the highest overall average.

# create performance labels:
# average >= 85 - "Excellent"
# average >= 70  "Good"
# average >= 50 "Pass"
# otherwise "Fail"

# I

# Extract students whose average is above the overall average.

In [ ]:
# Find the student index having the highest overall average.
averages = np.average(a, axis = 1)
print(np.argmax(averages))
max_average = np.max(averages)
print(max_average)

4
84.75


In [ ]:
np.where(averages >= 85,"excellent",np.where(averages>=70,"good",np.where(averages>=50,"pass","fail")))

array(['good', 'good', 'good', 'good', 'good', 'good'], dtype='<U9')

In [ ]:
# Extract students whose average is above the overall average.
overall_average = np.mean(scores)
np.where(averages > overall_average,"yes","no")

array(['no', 'yes', 'no', 'yes', 'yes', 'no'], dtype='<U3')

In [ ]:
# Extract the last two assessments of every student.
# a[:,-2:]

# Flatten the complete matri
d = a.flatten()



# Calculate the percentage of all assessment scores that are above 80.
a = len(scores[scores> 80])
total = len(scores)

a/total * 100

45.83333333333333

In [ ]:
# A company's monthly sales for one year are:

sales = np. array([
120000, 135000, 128000, 150000,
160000, 172000, 165000, 180000,
195000, 210000, 205000, 225000
])

# Calculate the average monthly sales.
print(np.mean(sales))

# Find the median sales.
print(np.median(sales))

# Find the month with the highest sales.
print(np.argmax(sales)+1)

# Calculate the standard deviation.
print(np.std(sales))



170416.66666666666
168500.0
12
32392.021479919335


In [ ]:
# Create a forecast for the next 6 months using np. linspace() between
# the minimum observed sales
# and 20% above the maximum observed sales.

# I
# Round the forecast values to the nearest rupee.

# Combine the original sales and forecast into one 18-element array.


# Calculate the average sales for each row.

# Identify values that are greater than the overall median.


In [ ]:
forecast = np.linspace(sales[0],1.20*sales[11],6)

In [ ]:
forecast

array([120000., 150000., 180000., 210000., 240000., 270000.])

In [ ]:
# Combine the original sales and forecast into one 18-element array.
new_sales = np.append(sales,forecast)


# Reshape the combined array into 3 * 6
reshaped = new_sales.reshape(3,6)

# Calculate the average sales for each row.
averages1 = np.average(reshaped, axis = 1)


# Identify values that are greater than the overall median.


In [ ]:
new_sales

array([120000., 135000., 128000., 150000., 160000., 172000., 165000.,
       180000., 195000., 210000., 205000., 225000., 120000., 150000.,
       180000., 210000., 240000., 270000.])

In [ ]:
reshaped

array([[120000., 135000., 128000., 150000., 160000., 172000.],
       [165000., 180000., 195000., 210000., 205000., 225000.],
       [120000., 150000., 180000., 210000., 240000., 270000.]])

In [ ]:
averages1

array([144166.66666667, 196666.66666667, 195000.        ])