<a href="https://colab.research.google.com/github/AnishShrestha09/pandas/blob/main/numpy5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
marks = np.array([70,80,65,90,75])

In [ ]:
marks[1:3] # last index is excluded

array([80, 65])

In [ ]:
marks[2:4]

array([65, 90])

In [ ]:
marks[0:4:2] #start,end,step

array([70, 65])

In [ ]:
marks[:3] # starting is zero

array([70, 80, 65])

In [ ]:
marks[3:] #end is last index

array([90, 75])

In [ ]:
marks[::] # start end step is default means 1

array([70, 80, 65, 90, 75])

In [ ]:
marks[::2] # print all the alternate elements

array([70, 65, 75])

In [ ]:
numbers = np.array([10, 20, 30, 40, 50, 60, 70])

print(numbers[1:4]) # 20 30 40
print(numbers[2:6]) # 30 40 50 60
print(numbers[0:3]) # 10 20 30

[20 30 40]
[30 40 50 60]
[10 20 30]


In [ ]:
numbers = np.array([10,20, 30, 40, 50])

print(numbers[2:]) # 30 40 50

[30 40 50]


In [ ]:
sales = np.array([100, 150, 200, 250, 300, 350])

print(sales[-3:]) # 250 300 350

[250 300 350]


In [ ]:
sales = np.array([100, 150, 200, 250, 300, 350])

print(sales[ :- 2]) # 100, 150, 200, 250

[100 150 200 250]


In [ ]:
numbers = np.array([10,20,30,40, 50, 60])

print(numbers [ :: 3]) #10 40

[10 40]


In [ ]:
# reverse the given array
numbers[::-1] # -1 is the step always come from backward

array([60, 50, 40, 30, 20, 10])

In [ ]:
marks = np.array([
[70,80,90,85],
[60,75,85,88],
[88, 92, 95,90],
[65,70,80,75]

])

In [ ]:
# get the marks of two rows
marks[:2]

array([[70, 80, 90, 85],
       [60, 75, 85, 88]])

In [ ]:
# second and third row
marks[1:3]

array([[60, 75, 85, 88],
       [88, 92, 95, 90]])

In [ ]:
# all rows and first 2 columns
marks[: ,:2] # first part is for row and other column

array([[70, 80],
       [60, 75],
       [88, 92],
       [65, 70]])

In [ ]:
# all row last and second last column
marks[:,-2:]

array([[90, 85],
       [85, 88],
       [95, 90],
       [80, 75]])

In [ ]:
marks[1:3,1:3]

array([[75, 85],
       [92, 95]])

In [ ]:
sales = np.array([
[100, 120, 150, 180],
[200, 220, 250, 270],
[150, 170, 190, 210]
])
print(sales[:, 1:3] * 1.10) # predict the output

[[132. 165.]
 [242. 275.]
 [187. 209.]]


In [ ]:
sales_ = sales[:,1:3]
withvat = sales_ * 1.1
print(withvat)

[[132. 165.]
 [242. 275.]
 [187. 209.]]


In [ ]:
prices = np. array([
1000, 1500, 2000, 2500, 3000, 3500
])
# product 3 - 5 receive 10 % discount
prices[2:5] * 0.9

array([1800., 2250., 2700.])

# DPP practice

In [ ]:
# A company has recorded its monthly revenue for the first 6 months:

# import numpy as np

# revenue = np.array([120000, 135000, 142000, 150000, 165000, 172000])

# Write a NumPy program to:

# Display the revenue of the third month.
# Display the revenue of the last month using negative indexing.
# Select the revenue from Month 2 to Month 5 using slicing.
# Increase the revenue of the last 3 months by 10%.
# Display the final revenue array.

In [1]:
import numpy as np

revenue = np.array([120000, 135000, 142000, 150000, 165000, 172000])

In [2]:
# Display the revenue of the third month.
revenue[2]

np.int64(142000)

In [6]:
# Display the revenue of the last month using negative indexing.
revenue[-1]

np.int64(172000)

In [7]:
# Select the revenue from Month 2 to Month 5 using slicing.
revenue[1:5]


array([135000, 142000, 150000, 165000])

In [11]:
# Increase the revenue of the last 3 months by 10%.
revenue[-3:] =1.1 * revenue[-3:]

In [12]:
# Display the final revenue array.
revenue

array([120000, 135000, 142000, 165000, 181500, 189200])

In [13]:
# A store has the following product prices:

# prices = np.array([500, 750, 1200, 1500, 2000, 2500])

# Write a program to:

# Display the first three prices.
# Display the last two prices.
# Apply a 15% discount only to products at indexes 2 through 4.
# Add ₹50 to the price of the first product.
# Display the updated prices.

In [18]:
# Display the first three prices.
prices = np.array([500, 750, 1200, 1500, 2000, 2500])
prices[:3]

array([ 500,  750, 1200])

In [19]:
# Display the last two prices.
prices[-2:]

array([2000, 2500])

In [22]:
# Apply a 15% discount only to products at indexes 2 through 4.
prices[2:5] = 0.85 * prices[2:5]

In [23]:
# Add ₹50 to the price of the first product.
prices[0] += 50

In [24]:
# Display the updated prices.
prices

array([ 550,  750, 1020, 1275, 1700, 2500])

In [24]:
# An electricity company wants to estimate the monthly electricity consumption
# of a household for 6 months.

# The expected consumption is:

# [180, 220, 195, 250, 280, 240] units.

# The company expects consumption to increase by 8% during the next billing cycle.

# Tasks
# Create a NumPy array for the consumption.
# Find the consumption in the 4th month.
# Extract the consumption of the last 3 months.
# Create a new array containing the expected consumption after an 8% increase.

In [25]:
# Create a NumPy array for the consumption.
consumption = np.array([180, 220, 195, 250, 280, 240] )

In [26]:
# Find the consumption in the 4th month.
consumption[3]

np.int64(250)

In [27]:
# Extract the consumption of the last 3 months.
consumption[-3:]

array([250, 280, 240])

In [28]:
# Create a new array containing the expected consumption after an 8% increase.
exp_consumption = 1.08 * consumption

In [29]:
exp_consumption

array([194.4, 237.6, 210.6, 270. , 302.4, 259.2])

In [30]:
# A factory operates .for 30 days and wants to create a production schedule
# .starting from 500 units per.day and gradually increasing to 1,500 units per day.

# .Tasks
# Generate.exactly.30 production targets .using.np. linspace().
# Create.day numbers .from 1.to 30 using.np. arange().
# Display the first.5 production targets.
# Display.the last .5.production targets.
# .Increase every production target by 10%.
# t.Display the first .5 .updated targets.

In [45]:
production_schedule = np.linspace(500,1500,30)

In [46]:
production_schedule

array([ 500.        ,  534.48275862,  568.96551724,  603.44827586,
        637.93103448,  672.4137931 ,  706.89655172,  741.37931034,
        775.86206897,  810.34482759,  844.82758621,  879.31034483,
        913.79310345,  948.27586207,  982.75862069, 1017.24137931,
       1051.72413793, 1086.20689655, 1120.68965517, 1155.17241379,
       1189.65517241, 1224.13793103, 1258.62068966, 1293.10344828,
       1327.5862069 , 1362.06896552, 1396.55172414, 1431.03448276,
       1465.51724138, 1500.        ])

In [43]:
days = np.arange(1,31)

In [44]:
days

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [47]:
# Display the first.5 production targets.
production_schedule[:5]

array([500.        , 534.48275862, 568.96551724, 603.44827586,
       637.93103448])

In [48]:
# Display.the last .5.production targets.
production_schedule[-5:]

array([1362.06896552, 1396.55172414, 1431.03448276, 1465.51724138,
       1500.        ])

In [49]:
# .Increase every production target by 10%.
production_schedule *= 1.1
print(production_schedule)

[ 550.          587.93103448  625.86206897  663.79310345  701.72413793
  739.65517241  777.5862069   815.51724138  853.44827586  891.37931034
  929.31034483  967.24137931 1005.17241379 1043.10344828 1081.03448276
 1118.96551724 1156.89655172 1194.82758621 1232.75862069 1270.68965517
 1308.62068966 1346.55172414 1384.48275862 1422.4137931  1460.34482759
 1498.27586207 1536.20689655 1574.13793103 1612.06896552 1650.        ]


In [50]:
# t.Display the first .5 .updated targets.
production_schedule[:5]

array([550.        , 587.93103448, 625.86206897, 663.79310345,
       701.72413793])

In [51]:
# A college records marks of 5 students in 4 subjects.

# marks = np.array([
# [72, 85,90,78],
# [65, 70,75,80],
# [88, 92, 95, 90],
# [55,65,60,70],
# [78, 82, 85,88]

# ])

# Each row represents a student and each column represents a subject.

# Tasks
# Determine the number of dimensions.
# Determine the number of students and subjects using shape.
# Determine the total number of marks using size.
# Display the complete marks of the 3rd student.
# Display marks of all students in the 2nd subject.
# Extract marks of the first 3 students in the first 2 subjects.
# Increase the marks of the last 2 students in the 4th subject by 5.

In [52]:
marks = np.array([
[72, 85,90,78],
[65, 70,75,80],
[88, 92, 95, 90],
[55,65,60,70],
[78, 82, 85,88]

])

In [54]:
# Determine the number of dimensions.
print(marks.ndim)

# Determine the number of students and subjects using shape.
print(marks.shape[0]) # students
print(marks.shape[1]) # subjects

# Determine the total number of marks using size.
print(marks.size)

# Display the complete marks of the 3rd student.
print(marks[2])

# Display marks of all students in the 2nd subject.
print(marks[:,1])

# Extract marks of the first 3 students in the first 2 subjects.
print(marks[:3,:2])

# Increase the marks of the last 2 students in the 4th subject by 5.
marks[-2:,3] += 5
print(marks)

2
5
4
20
[88 92 95 90]
[85 70 92 65 82]
[[72 85]
 [65 70]
 [88 92]]
[[72 85 90 78]
 [65 70 75 80]
 [88 92 95 90]
 [55 65 60 75]
 [78 82 85 98]]


In [55]:
# A restaurant stores prices of 6 menu items:

# prices = np.array([120, 180, 250, 300, 450, 600])

# The restaurant wants to run different pricing experiments.

# Tasks
# Add ₹20 to the first two items.
# Give a 10% discount to items 3, 4 and 5.
# Keep the last item unchanged.
# Display the first 3 prices after modification.
# Display the last 2 prices.

In [57]:
# Tasks
# Add ₹20 to the first two items.
prices = np.array([120, 180, 250, 300, 450, 600])
prices[:2]+=20
print(prices)

# Give a 10% discount to items 3, 4 and 5.
prices[2:5] = 0.9 * prices[2:5]
print(prices)
# Keep the last item unchanged.


# Display the first 3 prices after modification.
print(prices[:3])

# Display the last 2 prices.
print(prices[-2:])


[140 200 250 300 450 600]
[140 200 225 270 405 600]
[140 200 225]
[405 600]


In [58]:
# A machine records temperature every hour:

# temperature = np.array([
# 28, 29, 30, 31, 33, 35,
# 36, 35, 34, 32, 30, 29

# Tasks
# Extract readings from the first 6 hours.
# the last 6 hours.
# readings from every alternate hour.
# third hour.
# the complete temperature sequence.
# Extract the last 4 readings in reverse order.

# Extract readings from every third hour.
# Reverse the complete temperature sequence.
# Extract the last 4 readings in reverse order.



In [59]:
temperature = np.array([
28, 29, 30, 31, 33, 35,
36, 35, 34, 32, 30, 29
])

In [60]:
temperature[5:]

array([35, 36, 35, 34, 32, 30, 29])

In [61]:
temperature[-6:]


array([36, 35, 34, 32, 30, 29])

In [62]:
# readings from every alternate hour.
temperature[::2]


array([28, 30, 33, 36, 34, 30])

In [63]:
# third hour.
temperature[2]


np.int64(30)

In [67]:
# Extract readings from every third hour.
temperature[::3]

array([28, 31, 36, 32])

In [66]:
# Reverse the complete temperature sequence.
temperature[::-1]

array([29, 30, 32, 34, 35, 36, 35, 33, 31, 30, 29, 28])

In [68]:

# Extract the last 4 readings in reverse order.
temperature[-1:-5:-1]

array([29, 30, 32, 34])