<a href="https://colab.research.google.com/github/AnishShrestha09/numppy/blob/main/numpy13.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# The coordinates of eight delivery locations are:
import numpy as np
points = np.array([
[3,4],
[5,12],
[8,15],
[7,24],
[9,40],
[12,35],
[15,20],
[6,8]
])
# Each row contains:

# [x, y]

# Calculate distance from the origin using:

# distance = V(x2 +y2)

# I

In [8]:
# Extract x and y coordinates.
x = points[:,0] # x coordinate
y = points[:,1] # y coordinate

# Calculate distance for every location.
distance = np.sqrt(x**2 + y**2)
print(distance)

# Round distances to 2 decimals.
print(np.round(distance,2))

# Find nearest and farthest location.
print(np.max(distance))
print(np.min(distance))

# Find average distance.
print(np.mean(distance))

# Find locations above average distance.
criteria = distance > np.mean(distance)
print(points[criteria])

# Categorize:
# if >= 30 + Long
# elseif >= 15 - Medium
print(np.where(distance> 30,"long",np.where(distance > 15,"medium","short")))

[ 5. 13. 17. 25. 41. 37. 25. 10.]
[ 5. 13. 17. 25. 41. 37. 25. 10.]
41.0
5.0
21.625
[[ 7 24]
 [ 9 40]
 [12 35]
 [15 20]]
['short' 'short' 'medium' 'medium' 'long' 'long' 'medium' 'short']


In [13]:
# Find percentage of Long-distance deliveries.

a = np.where(distance> 30,"long",np.where(distance > 15,"medium","short"))
b = len(a[a=="long"])
c = len(a)

d = b/c * 100
print(d)

# Flatten the coordinate array.
print(points.flatten())

# Find the size of the flattened array.
print(points.size)

25.0
[ 3  4  5 12  8 15  7 24  9 40 12 35 15 20  6  8]
16


In [20]:
patients = np.array([
[101, 120, 85, 98],
[102, 135, 92, 96],
[103, 110, 78, 99],
[104, 150, 88, 94],
[105, 125, 95, 97],
[106, 160, 82, 93],
[107, 115, 90,98],
[108, 145, 87, 95],
[109, 130, 91, 96],
[110, 155, 80,92]
])
# Patient_ID, Heart_Rate, Oxygen_Level, Recovery_Score

# Calculate average heart rate.

print(np.mean(patients[:,1]))
# Calculate median oxygen level.
print(np.median(patients[:,2]))

# Find patients with heart rate above average AND oxygen below 90.
criteria = ((patients[:,1] >np.mean(patients[:,1])) & (patients[:,2]<90))
print(patients[criteria])


134.5
87.5
[[104 150  88  94]
 [106 160  82  93]
 [108 145  87  95]
 [110 155  80  92]]


In [28]:
# Categorize recovery:
# >= 97 + Excellent
# >= 95 + Stable
# Otherwise + Monitor
a =patients[:,3]
b = np.where(a >= 97,"excellent",np.where(a>=95,"stable","monitor"))
print(b)
# Count each category.
excellent = len(b[b=="excellent"])
stable = len(b[b=="stable"])
monitor = len(b[b=="monitor"])
print(excellent,stable,monitor)


# Find patient with highest heart rate.
highest = np.argmax(patients[:,1])
patients[highest]

# Calculate standard deviation of oxygen levels.
print(np.std(patients[:,1]))

# Find oxygen levels more than 1 standard deviation below the mean.


# Extract the last 3 patients.

# Flatten the measurement data and calculate its mean.

['excellent' 'stable' 'excellent' 'monitor' 'excellent' 'monitor'
 'excellent' 'stable' 'stable' 'monitor']
4 3 3
16.5
