<a href="https://colab.research.google.com/github/AnishShrestha09/numppy/blob/main/numpy9.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
marks = np.array([10,20,30,50,90,90,90])

In [ ]:
marks > 80

array([False, False, False, False,  True,  True,  True])

In [ ]:
marks[marks> 80]

array([90, 90, 90])

In [ ]:
np.where(marks> 70,"good"," average")

array([' average', ' average', ' average', ' average', 'good', 'good',
       'good'], dtype='<U8')

In [ ]:
# Suppose students scoring below 50 get 5 grace marks.
np.where(marks< 50,marks+5,marks)

array([15, 25, 35, 50, 90, 90, 90])

In [ ]:
# Suppose products costing more than ₹1,000 receive a 10% discount.

prices= np.array([500, 1200, 800, 2500, 1500])


n_prices = np.where(prices>1000,prices*0.1,0)


print(prices-n_prices)
print(n_prices)

[ 500. 1080.  800. 2250. 1350.]
[  0. 120.   0. 250. 150.]


In [ ]:
salary = np.array([25000, 45000, 75000, 32000, 90000])

# Salary >= 50000 + High
# Salary < 50000 + Standard

In [ ]:
standard = np.where(salary>= 50000,"high","low")
print(standard)

['low' 'low' 'high' 'low' 'high']


In [ ]:
marks

array([10, 20, 30, 50, 90, 90, 90])

In [ ]:
# 90 or above excellecnt
# 50-89 pass
# below 50 fail

In [ ]:
np.where(marks>=90,"excellent",np.where(marks>=50,"pass","fail"))

array(['fail', 'fail', 'fail', 'pass', 'excellent', 'excellent',
       'excellent'], dtype='<U9')

In [ ]:
# sales = np.array([950000, 650000, 300000, 800000, 450000])

# Categories:

# = 800000 - "Top Performer"

# = 500000 - "Good Performer"

# otherwise - "Needs Improvement"

In [ ]:
sales = np.array([950000, 650000, 300000, 800000, 450000])
np.where(sales>800000,"topperformer",np.where(sales>500000,"goodperformer","needs ivmprovement"))

array(['topperformer', 'goodperformer', 'needs ivmprovement',
       'goodperformer', 'needs ivmprovement'], dtype='<U18')

In [ ]:
# Suppose a loan applicant must satisfy both:

# salary >= ₹50,000
# credit score >= 700

# then approve, else reject

# salary = np.array([60000, 40000, 75000, 55000, 30000])
# credit_score = np.array([720, 750, 680, 710, 800])

In [ ]:
salary = np.array([60000, 40000, 75000, 55000, 30000])
credit_score = np.array([720, 750, 680, 710, 800])

np.where((salary>50000)& (credit_score>=700),"approve","reject")

array(['approve', 'reject', 'reject', 'approve', 'reject'], dtype='<U7')

In [ ]:
# Suppose a customer receives free shipping if:

# order value >= ₹1,000

# OR

# customer is a premiun customer.
# order_value = np.array([500, 1200, 700, 800, 1500])
# premium = np.array([False, False, True, False, True])

In [ ]:
order_value = np.array([500, 1200, 700, 800, 1500])
premium = np.array([False, False, True, False, True])

np.where((order_value>=1000)|(premium==True),"freeshipping","needmoney")

array(['needmoney', 'freeshipping', 'freeshipping', 'needmoney',
       'freeshipping'], dtype='<U12')

In [ ]:
students = np. array([
[101, 78, 85, 92],
[102, 45, 55,60],
[103, 91, 88, 95],
[104, 62,70,68],
[105, 35, 42, 50]
])
# Student ID | Python | SQL | ML

In [ ]:
# Let's classify students as:

# Average >= 85 - Excellent
# Average >= 60 - Good
# Average >= 50 - Pass

In [ ]:
marks = students[:,1:]
avg = np.average(marks, axis=1)
np.where(avg>=85,"excellent",np.where(avg>=60,"good",np.where(avg>=50,"pass","fail")))

array(['excellent', 'pass', 'excellent', 'good', 'fail'], dtype='<U9')

In [42]:
# A business records revenue for 12 months:

# revenue = np.array([
# 120000, 135000, 128000, 145000,
# 150000, 138000, 160000, 172000,
# 155000, 148000, 180000, 195000
# ])
# Find:

# Average monthly revenue
# Highest revenue
# Lowest revenue
# Month index with highest revenue
# Month index with lowest revenue
# Total annual revenue
# Difference between highest and lowest revenue

In [43]:
import numpy as np
revenue = np.array([
120000, 135000, 128000, 145000,
150000, 138000, 160000, 172000,
155000, 148000, 180000, 195000
])

In [46]:
# Average monthly revenue
np.average(revenue)

# Highest revenue
print(np.max(revenue))

# Lowest revenue
print(np.min(revenue))


# Month index with highest revenue
print(np.argmax(revenue))


# Month index with lowest revenue
print(np.argmin(revenue))


# Total annual revenue
print(np.sum(revenue))

# Difference between highest and lowest revenue
print(np.max(revenue)-np.argmin(revenue))


195000
120000
11
0
1826000
195000


In [53]:
#  show the quaterly total revenue
quarter1 = revenue[:3]
quarter2 = revenue[3:6]
quarter3 = revenue[6:9]
quarter4 = revenue[9:]
quarter = []
quarter.append(quarter1)
quarter.append(quarter2)
quarter.append(quarter3)
quarter.append(quarter4)

print(quarter)



[array([120000, 135000, 128000]), array([145000, 150000, 138000]), array([160000, 172000, 155000]), array([148000, 180000, 195000])]


In [54]:
# The following array contains sales made by 4 salespeople across 3 months.

# sales = np.array([
# [120, 150, 180],
# [200, 170,160],
# [100, 140, 130],
# [180, 190, 210]
# ])

# Rows represent salespeople and columns represent months.

# Find:

# Total sales by each salesperson
# Average sales by each salesperson
# Total sales for each month
# Average sales for each month
# Highest sales achieved by each salesperson

In [55]:
sales = np.array([
[120, 150, 180],
[200, 170,160],
[100, 140, 130],
[180, 190, 210]
])

In [58]:
# Total sales by each salesperson
print(np.sum(sales, axis= 1))

# Average sales by each salesperson
print(np.mean(sales, axis= 1))

# Total sales for each month
print(np.sum(sales, axis =0))

# Average sales for each month
print(np.mean(sales, axis= 0))

# Highest sales achieved by each salesperson
print(np.max(sales,axis=1))

[450 530 370 580]
[150.         176.66666667 123.33333333 193.33333333]
[600 650 680]
[150.  162.5 170. ]
[180 200 140 210]


In [59]:
# Consider:

# employees = np. array([
# [101, 35000, 2],
# [102, 48000, 4],
# [103, 62000, 6],
# [104,40000, 3],
# [105, 75000,8],
# [106, 55000, 5]
# ])
# Columns represent:

# Employee ID | Salary | experience

# Find:

# Employees earning more than ₹50,000.
# Employees with more than 4 years of experience.
# Employees earning more than ₹50,000 AND having more than 4 years of experience.
# Average salary of employees satisfying condition 3.
# Employee with the highest salary.
# Employees earning below the median salary.



In [60]:
employees = np. array([
[101, 35000, 2],
[102, 48000, 4],
[103, 62000, 6],
[104,40000, 3],
[105, 75000,8],
[106, 55000, 5]
])


In [75]:
# Employees earning more than ₹50,000.
print(employees[:,1][employees[:,1]> 50000])

# Employees with more than 4 years of experience.
print(employees[:,2][employees[:,2]> 4])


# Employees earning more than ₹50,000 AND having more than 4 years of experien
print(employees[(employees[:,1] >50000) & (employees[:,2]> 4)])

# Average salary of employees satisfying condition 3.
print(np.average(employees[:,1]))

# Employee with the highest salary.
print(np.max(employees[:,1]))

# Employees earning below the median salary.
employees[:,1] > np.median(employees[:,1])
print(employees[employees[:,1] > np.median(employees[:,1])])

[62000 75000 55000]
[6 8 5]
[[  103 62000     6]
 [  105 75000     8]
 [  106 55000     5]]
52500.0
75000
[[  103 62000     6]
 [  105 75000     8]
 [  106 55000     5]]
