<a href="https://colab.research.google.com/github/AnishShrestha09/numppy/blob/main/numpy9.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
marks = np.array([10,20,30,50,90,90,90])

In [3]:
marks > 80

array([False, False, False, False,  True,  True,  True])

In [4]:
marks[marks> 80]

array([90, 90, 90])

In [5]:
np.where(marks> 70,"good"," average")

array([' average', ' average', ' average', ' average', 'good', 'good',
       'good'], dtype='<U8')

In [15]:
# Suppose students scoring below 50 get 5 grace marks.
np.where(marks< 50,marks+5,marks)

array([15, 25, 35, 50, 90, 90, 90])

In [18]:
# Suppose products costing more than ₹1,000 receive a 10% discount.

prices= np.array([500, 1200, 800, 2500, 1500])


n_prices = np.where(prices>1000,prices*0.1,0)


print(prices-n_prices)
print(n_prices)

[ 500. 1080.  800. 2250. 1350.]
[  0. 120.   0. 250. 150.]


In [19]:
salary = np.array([25000, 45000, 75000, 32000, 90000])

# Salary >= 50000 + High
# Salary < 50000 + Standard

In [20]:
standard = np.where(salary>= 50000,"high","low")
print(standard)

['low' 'low' 'high' 'low' 'high']


In [21]:
marks

array([10, 20, 30, 50, 90, 90, 90])

In [22]:
# 90 or above excellecnt
# 50-89 pass
# below 50 fail

In [24]:
np.where(marks>=90,"excellent",np.where(marks>=50,"pass","fail"))

array(['fail', 'fail', 'fail', 'pass', 'excellent', 'excellent',
       'excellent'], dtype='<U9')

In [25]:
# sales = np.array([950000, 650000, 300000, 800000, 450000])

# Categories:

# = 800000 - "Top Performer"

# = 500000 - "Good Performer"

# otherwise - "Needs Improvement"

In [28]:
sales = np.array([950000, 650000, 300000, 800000, 450000])
np.where(sales>800000,"topperformer",np.where(sales>500000,"goodperformer","needs ivmprovement"))

array(['topperformer', 'goodperformer', 'needs ivmprovement',
       'goodperformer', 'needs ivmprovement'], dtype='<U18')

In [29]:
# Suppose a loan applicant must satisfy both:

# salary >= ₹50,000
# credit score >= 700

# then approve, else reject

# salary = np.array([60000, 40000, 75000, 55000, 30000])
# credit_score = np.array([720, 750, 680, 710, 800])

In [30]:
salary = np.array([60000, 40000, 75000, 55000, 30000])
credit_score = np.array([720, 750, 680, 710, 800])

np.where((salary>50000)& (credit_score>=700),"approve","reject")

array(['approve', 'reject', 'reject', 'approve', 'reject'], dtype='<U7')

In [31]:
# Suppose a customer receives free shipping if:

# order value >= ₹1,000

# OR

# customer is a premiun customer.
# order_value = np.array([500, 1200, 700, 800, 1500])
# premium = np.array([False, False, True, False, True])

In [34]:
order_value = np.array([500, 1200, 700, 800, 1500])
premium = np.array([False, False, True, False, True])

np.where((order_value>=1000)|(premium==True),"freeshipping","needmoney")

array(['needmoney', 'freeshipping', 'freeshipping', 'needmoney',
       'freeshipping'], dtype='<U12')

In [35]:
students = np. array([
[101, 78, 85, 92],
[102, 45, 55,60],
[103, 91, 88, 95],
[104, 62,70,68],
[105, 35, 42, 50]
])
# Student ID | Python | SQL | ML

In [36]:
# Let's classify students as:

# Average >= 85 - Excellent
# Average >= 60 - Good
# Average >= 50 - Pass

In [41]:
marks = students[:,1:]
avg = np.average(marks, axis=1)
np.where(avg>=85,"excellent",np.where(avg>=60,"good",np.where(avg>=50,"pass","fail")))

array(['excellent', 'pass', 'excellent', 'good', 'fail'], dtype='<U9')