<a href="https://colab.research.google.com/github/AnishShrestha09/numppy/blob/main/numpy8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
marks = np.array([10,20,30,40])

In [ ]:
marks

array([10, 20, 30, 40])

In [ ]:
70 > 80

False

In [ ]:
# Write a code to filter in only the marks > 10

In [ ]:
marks > 10

array([False,  True,  True,  True])

In [ ]:
marks[[False,  True,  True,  True]]

array([20, 30, 40])

In [ ]:
marks[marks>10]

array([20, 30, 40])

In [ ]:
# temperature = np.array([
# 24, 28, 31, 35, 29, 22, 37, 30

# ])

# temp atleast 32

In [ ]:
temperature = np.array([
24, 28, 31, 35, 29, 22, 37, 30
])

In [ ]:
temperature > 32

array([False, False, False,  True, False, False,  True, False])

In [ ]:
temperature[temperature > 32]

array([35, 37])

In [ ]:
# prices = np.array([
# 499, 799, 1299, 2499, 3999, 599
# ])
# Prices between 600 and 1000.

In [ ]:
prices = np.array([
499, 799, 1299, 2499, 3999, 599
])

In [ ]:
(prices > 600 ) & (prices <1000)

array([False,  True, False, False, False, False])

In [ ]:

prices[(prices > 600 ) & (prices <1000)]

array([799])

In [ ]:
# less than 600 or greater than 1000

In [ ]:
prices[(prices < 600 ) | (prices >1000)]


array([ 499, 1299, 2499, 3999,  599])

In [ ]:
#show prices not greater than 900

In [ ]:
prices[(prices < 900) ]


array([499, 799, 599])

In [ ]:
prices[~(prices > 900) ]

array([499, 799, 599])

In [ ]:
marks = np.array([
[72,85,90],
[55,60,65],
[88,92,95],
[45, 50,48]
])

In [ ]:
# filter marks > 70

In [ ]:
marks > 70

array([[ True,  True,  True],
       [False, False, False],
       [ True,  True,  True],
       [False, False, False]])

In [ ]:
marks[marks > 70]

array([72, 85, 90, 88, 92, 95])

In [ ]:
sales = np. array([
[100, 200, 300],
[400, 500,600],
[150, 250, 350]
])
# Find values greater than 200 only in the first row:

In [ ]:
sales[:,0] > 200

array([False,  True, False])

In [ ]:
sales[0] > 200

array([False, False,  True])

In [ ]:
sales[0][sales[0] >=200]

array([200, 300])

In [ ]:
products = np.array([
[101, 500],
[102, 1200],
[103, 800],
[104,1500]
])

####We want products whose price is greater than ₹1,000.



In [ ]:
products[:,1]>1000

array([False,  True, False,  True])

In [ ]:

products[:,1][products[:,1]>1000]

array([1200, 1500])

In [ ]:
# An electricity board records the monthly electricity consumption of a household for one year:

# consumption = np.array([
# 180, 220, 195, 250,
# 280, 310, 295, 270,|
# 240, 210, 190, 230
# ])
# Perform the following:

# Find the total annual consumption.
# Calculate average monthly consumption.
# Find the highest and lowest consumption.
# W
# Find the month index with the highest consumption.
# Extract the first 6 months using slicing.
# Extract alternate months.
# Find all months where consumption was greater than the annual average.
# Calculate the percentage increase required if next year's consumption is expected to be 8% higher.

In [ ]:
consumption = np.array([
180, 220, 195, 250,
280, 310, 295, 270,
240, 210, 190, 230
])

In [ ]:

# Find the total annual consumption.
print(np.sum(consumption))

# Calculate average monthly consumption.
print(np.average(consumption))

# Find the highest and lowest consumption.
print(np.max(consumption))
print(np.min(consumption))

# Find the month index with the highest consumption.
print(np.argmax(consumption))

# Extract the first 6 months using slicing.
print(consumption[0:6])

# Extract alternate months.
print(consumption[::2])



# Find all months where consumption was greater than the annual average.
# Calculate the percentage increase required if next year's consumption is expected to be 8% higher.

2870
239.16666666666666
310
180
5
[180 220 195 250 280 310]
[180 195 280 295 240 190]


In [1]:
# An online store has the following product prices:

# prices = np. array([
# 499.50, 799.90, 1299.75,
# 2499.50, 3999.90, 599.25,
# 899.80, 1599.40
# ])
# Perform:

# Round prices to the nearest whole number.
# Find products costing more than ₹1,000.
# Calculate a 15% discount only on products costing more than ₹1,000.
# Calculate the average discounted price of those products.
# Find the most expensive original product.
# Extract the last 4 products.
# Calculate the square root of the final prices and round them to 2 decimal places.


In [2]:
import numpy as np

In [8]:
prices = np. array([
499.50, 799.90, 1299.75,
2499.50, 3999.90, 599.25,
899.80, 1599.40
])

In [9]:
# Round prices to the nearest whole number.
roundprice = np.around(prices)
print(roundprice)

[ 500.  800. 1300. 2500. 4000.  599.  900. 1599.]


In [10]:
# Find products costing more than ₹1,000.

prices[prices > 1000]

array([1299.75, 2499.5 , 3999.9 , 1599.4 ])

In [6]:
# Calculate a 15% discount only on products costing more than ₹1,000.
prices[prices > 1000] = 85 * prices[prices > 1000]


In [7]:
prices

array([   499.5 ,    799.9 , 110478.75, 212457.5 , 339991.5 ,    599.25,
          899.8 , 135949.  ])

In [12]:
# Calculate the average discounted price of those products.
np.average( 0.85 * prices[prices > 1000] )

np.float64(1997.191875)

In [13]:
# Find the most expensive original product.
np.max(prices)

np.float64(3999.9)

In [14]:
# Extract the last 4 products.
prices[-4:]

array([3999.9 ,  599.25,  899.8 , 1599.4 ])

In [16]:
# Calculate the square root of the final prices and round them to 2 decimal places.
np.round(np.sqrt(prices),2)

array([22.35, 28.28, 36.05, 49.99, 63.24, 24.48, 30.  , 39.99])