<a href="https://colab.research.google.com/github/AnishShrestha09/numppy/blob/main/numpy11.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

# A factory collects temperatures from 20 sensor readings:

temperature = np. array ([
28.5, 31.2, 29.8, 35.6, 38.1,
40.2, 27.9, 30.5, 42.3, 39.8,
36.4, 33.2, 29.1, 41.7, 44.2,
31.8, 34.5, 37.6, 26.9, 43.1
])

In [ ]:
# Calculate mean, median, minimum and maximum.
print(np.mean(temperature))
print(np.median(temperature))
print(np.max(temperature))

# Calculate variance and standard deviation.
print(np.square(np.std(temperature))) #variance
print(np.std(temperature))


# Find all temperatures more than one standard deviation above the mean.
print(temperature[temperature >np.std(temperature) ])

# Calculate the absolute difference between every temperature and the mean.
print(np.abs(temperature - np.mean(temperature)))

# Find the five readings having the largest deviation from the mean.
a = np.sort(temperature)
print("a")
print(a[-5:])

# Round all temperatures to the nearest whole number.
print(np.round(temperature))

35.12
35.05
44.2
29.2726
5.410415880503088
[28.5 31.2 29.8 35.6 38.1 40.2 27.9 30.5 42.3 39.8 36.4 33.2 29.1 41.7
 44.2 31.8 34.5 37.6 26.9 43.1]
[6.62 3.92 5.32 0.48 2.98 5.08 7.22 4.62 7.18 4.68 1.28 1.92 6.02 6.58
 9.08 3.32 0.62 2.48 8.22 7.98]
a
[40.2 41.7 42.3 43.1 44.2]
[28. 31. 30. 36. 38. 40. 28. 30. 42. 40. 36. 33. 29. 42. 44. 32. 34. 38.
 27. 43.]


In [ ]:
Categorize temperatures:
>= 40 "Critical"
>= 35 - "Warning"
Otherwise - "Normal"







In [ ]:
# Find the number and percentage of critical readings.
np.where(temperature>=40,"critical",np.where(temperature >=35,"warning","normal"))

critical = len(temperature[temperature>=40 ])
total = len(temperature)

critical_per = critical/total * 100
print(critical,critical_per)

5 25.0


In [ ]:
# Reshape the readings into a 4 × 5 array.
a= temperature.reshape(4,5)
print(a)

[[28.5 31.2 29.8 35.6 38.1]
 [40.2 27.9 30.5 42.3 39.8]
 [36.4 33.2 29.1 41.7 44.2]
 [31.8 34.5 37.6 26.9 43.1]]


In [ ]:
# Find the average temperature for each row.
np.average(a,axis= 1)

array([32.64, 36.14, 36.92, 34.78])

In [ ]:
employees = np. array([
[101, 42000, 3, 450000],
[102, 65000, 6, 720000],
[103, 38000, 2, 300000],
[104, 90000, 8, 950000],
[105, 55000, 5,610000],
[106, 72000, 7,830000]

])

In [ ]:
# Columns represent:

# Employee_ID | Salary | Experience | Annual Sales

In [ ]:
# Find the employee with the highest annual sales.
# Find employees having at least 5 years experience AND sales above ₹600,000.
# Calculate bonus:
# Sales >= ₹800,000 - 10%
# Sales >= ₹600,000 -7%
# Otherwise + 3%

In [ ]:
# Extract salary, experience and annual sales.
employees[:,1:]

array([[ 42000,      3, 450000],
       [ 65000,      6, 720000],
       [ 38000,      2, 300000],
       [ 90000,      8, 950000],
       [ 55000,      5, 610000],
       [ 72000,      7, 830000]])

In [ ]:
# Calculate sales-to-salary ratio.
sales_to_salary = employees[:,-1]/employees[:,1]
print(sales_to_salary)

[10.71428571 11.07692308  7.89473684 10.55555556 11.09090909 11.52777778]


In [ ]:
# Find the employee with the highest annual sales.

print(employees[np.argmax(employees[:,-1])])

[   104  90000      8 950000]


In [ ]:
# Find employees having at least 5 years experience AND sales above ₹600,000.
print(employees[(employees[:,-1]> 600000)&(employees[:,-2] >=5 )])


[[   102  65000      6 720000]
 [   104  90000      8 950000]
 [   105  55000      5 610000]
 [   106  72000      7 830000]]


In [ ]:
# Calculate bonus:
# Sales >= ₹800,000 - 10%
# Sales >= ₹600,000 -7%
# Otherwise + 3%


bonus = np.where(employees[:,-1]> 800000,0.1*employees[:,-1],np.where(employees[:,-1]> 600000,0.07*employees[:,-1],0.03*employees[:,-1]))
print(bonus)

[13500. 50400.  9000. 95000. 42700. 83000.]


In [ ]:
# Calculate total bonus amount.
total_bonus = np.sum(total)
print(total_bonus)

# Find average salary of employees receiving a 10% bonus.
sales = employees[:,-1]
salary =employees[:,1]
print(sales)
avg = np.mean(employees[sales> 800000])
print(avg)

# Find median salary.
np.median(sales)

# Find employees whose salary is above median salary but experience is less than 6 years.
a = employees[(salary>np.median(salary))& employees[:,-2]<=6]
print(a)

# Round sales-to-salary ratio to 2 decimal places.


20
[450000 720000 300000 950000 610000 830000]
242778.125
[[   101  42000      3 450000]
 [   102  65000      6 720000]
 [   103  38000      2 300000]
 [   104  90000      8 950000]
 [   105  55000      5 610000]
 [   106  72000      7 830000]]
